<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Api\Admin\Controllers\AccountLogController;
use App\Api\Admin\Controllers\AdController;
use App\Api\Admin\Controllers\AdCustomController;
use App\Api\Admin\Controllers\AdminActionController;
use App\Api\Admin\Controllers\AdminLogController;
use App\Api\Admin\Controllers\AdminMessageController;
use App\Api\Admin\Controllers\AdminUserController;
use App\Api\Admin\Controllers\AdPositionController;
use App\Api\Admin\Controllers\AdsenseController;
use App\Api\Admin\Controllers\AffiliateLogController;
use App\Api\Admin\Controllers\AgencyController;
use App\Api\Admin\Controllers\AreaRegionController;
use App\Api\Admin\Controllers\ArticleCatController;
use App\Api\Admin\Controllers\ArticleController;
use App\Api\Admin\Controllers\AttributeController;
use App\Api\Admin\Controllers\AuctionLogController;
use App\Api\Admin\Controllers\AutoManageController;
use App\Api\Admin\Controllers\BackGoodsController;
use App\Api\Admin\Controllers\BackOrderController;
use App\Api\Admin\Controllers\BonusTypeController;
use App\Api\Admin\Controllers\BookingGoodsController;
use App\Api\Admin\Controllers\BrandController;
use App\Api\Admin\Controllers\CardController;
use App\Api\Admin\Controllers\CartController;
use App\Api\Admin\Controllers\CategoryController;
use App\Api\Admin\Controllers\CatRecommendController;
use App\Api\Admin\Controllers\CollectGoodsController;
use App\Api\Admin\Controllers\CommentController;
use App\Api\Admin\Controllers\CronsController;
use App\Api\Admin\Controllers\DeliveryGoodsController;
use App\Api\Admin\Controllers\DeliveryOrderController;
use App\Api\Admin\Controllers\EmailListController;
use App\Api\Admin\Controllers\EmailSendlistController;
use App\Api\Admin\Controllers\ErrorLogController;
use App\Api\Admin\Controllers\ExchangeGoodsController;
use App\Api\Admin\Controllers\FavourableActivityController;
use App\Api\Admin\Controllers\FeedbackController;
use App\Api\Admin\Controllers\FriendLinkController;
use App\Api\Admin\Controllers\GoodsActivityController;
use App\Api\Admin\Controllers\GoodsArticleController;
use App\Api\Admin\Controllers\GoodsAttrController;
use App\Api\Admin\Controllers\GoodsCatController;
use App\Api\Admin\Controllers\GoodsController;
use App\Api\Admin\Controllers\GoodsGalleryController;
use App\Api\Admin\Controllers\GoodsTypeController;
use App\Api\Admin\Controllers\GroupGoodsController;
use App\Api\Admin\Controllers\KeywordsController;
use App\Api\Admin\Controllers\LinkGoodsController;
use App\Api\Admin\Controllers\MailTemplatesController;
use App\Api\Admin\Controllers\MemberPriceController;
use App\Api\Admin\Controllers\NavController;
use App\Api\Admin\Controllers\OrderActionController;
use App\Api\Admin\Controllers\OrderGoodsController;
use App\Api\Admin\Controllers\OrderInfoController;
use App\Api\Admin\Controllers\PackageGoodsController;
use App\Api\Admin\Controllers\PackController;
use App\Api\Admin\Controllers\PayLogController;
use App\Api\Admin\Controllers\PaymentController;
use App\Api\Admin\Controllers\PluginsController;
use App\Api\Admin\Controllers\ProductsController;
use App\Api\Admin\Controllers\RegExtendInfoController;
use App\Api\Admin\Controllers\RegFieldsController;
use App\Api\Admin\Controllers\RegionController;
use App\Api\Admin\Controllers\RoleController;
use App\Api\Admin\Controllers\SearchengineController;
use App\Api\Admin\Controllers\ShippingAreaController;
use App\Api\Admin\Controllers\ShippingController;
use App\Api\Admin\Controllers\ShopConfigController;
use App\Api\Admin\Controllers\SnatchLogController;
use App\Api\Admin\Controllers\StatsController;
use App\Api\Admin\Controllers\SuppliersController;
use App\Api\Admin\Controllers\TagController;
use App\Api\Admin\Controllers\TemplateController;
use App\Api\Admin\Controllers\TopicController;
use App\Api\Admin\Controllers\UserAccountController;
use App\Api\Admin\Controllers\UserAddressController;
use App\Api\Admin\Controllers\UserBonusController;
use App\Api\Admin\Controllers\UserFeedController;
use App\Api\Admin\Controllers\UserRankController;
use App\Api\Admin\Controllers\UsersController;
use App\Api\Admin\Controllers\VirtualCardController;
use App\Api\Admin\Controllers\VolumePriceController;
use App\Api\Admin\Controllers\VoteController;
use App\Api\Admin\Controllers\VoteLogController;
use App\Api\Admin\Controllers\VoteOptionController;
use App\Api\Admin\Controllers\WholesaleController;
use Illuminate\Support\Facades\Route;

// 查询列表接口
Route::post('accountLog/query', [AccountLogController::class, 'query']);
// 新增接口
Route::post('accountLog/store', [AccountLogController::class, 'store']);
// 获取详情接口
Route::get('accountLog/show', [AccountLogController::class, 'show'])->name('accountLog.show');
// 更新接口
Route::put('accountLog/update', [AccountLogController::class, 'update']);
// 删除接口
Route::delete('accountLog/destroy', [AccountLogController::class, 'destroy']);
// 查询列表接口
Route::post('ad/query', [AdController::class, 'query']);
// 新增接口
Route::post('ad/store', [AdController::class, 'store']);
// 获取详情接口
Route::get('ad/show', [AdController::class, 'show'])->name('ad.show');
// 更新接口
Route::put('ad/update', [AdController::class, 'update']);
// 删除接口
Route::delete('ad/destroy', [AdController::class, 'destroy']);
// 查询列表接口
Route::post('adCustom/query', [AdCustomController::class, 'query']);
// 新增接口
Route::post('adCustom/store', [AdCustomController::class, 'store']);
// 获取详情接口
Route::get('adCustom/show', [AdCustomController::class, 'show'])->name('adCustom.show');
// 更新接口
Route::put('adCustom/update', [AdCustomController::class, 'update']);
// 删除接口
Route::delete('adCustom/destroy', [AdCustomController::class, 'destroy']);
// 查询列表接口
Route::post('adPosition/query', [AdPositionController::class, 'query']);
// 新增接口
Route::post('adPosition/store', [AdPositionController::class, 'store']);
// 获取详情接口
Route::get('adPosition/show', [AdPositionController::class, 'show'])->name('adPosition.show');
// 更新接口
Route::put('adPosition/update', [AdPositionController::class, 'update']);
// 删除接口
Route::delete('adPosition/destroy', [AdPositionController::class, 'destroy']);
// 查询列表接口
Route::post('adminAction/query', [AdminActionController::class, 'query']);
// 新增接口
Route::post('adminAction/store', [AdminActionController::class, 'store']);
// 获取详情接口
Route::get('adminAction/show', [AdminActionController::class, 'show'])->name('adminAction.show');
// 更新接口
Route::put('adminAction/update', [AdminActionController::class, 'update']);
// 删除接口
Route::delete('adminAction/destroy', [AdminActionController::class, 'destroy']);
// 查询列表接口
Route::post('adminLog/query', [AdminLogController::class, 'query']);
// 新增接口
Route::post('adminLog/store', [AdminLogController::class, 'store']);
// 获取详情接口
Route::get('adminLog/show', [AdminLogController::class, 'show'])->name('adminLog.show');
// 更新接口
Route::put('adminLog/update', [AdminLogController::class, 'update']);
// 删除接口
Route::delete('adminLog/destroy', [AdminLogController::class, 'destroy']);
// 查询列表接口
Route::post('adminMessage/query', [AdminMessageController::class, 'query']);
// 新增接口
Route::post('adminMessage/store', [AdminMessageController::class, 'store']);
// 获取详情接口
Route::get('adminMessage/show', [AdminMessageController::class, 'show'])->name('adminMessage.show');
// 更新接口
Route::put('adminMessage/update', [AdminMessageController::class, 'update']);
// 删除接口
Route::delete('adminMessage/destroy', [AdminMessageController::class, 'destroy']);
// 查询列表接口
Route::post('adminUser/query', [AdminUserController::class, 'query']);
// 新增接口
Route::post('adminUser/store', [AdminUserController::class, 'store']);
// 获取详情接口
Route::get('adminUser/show', [AdminUserController::class, 'show'])->name('adminUser.show');
// 更新接口
Route::put('adminUser/update', [AdminUserController::class, 'update']);
// 删除接口
Route::delete('adminUser/destroy', [AdminUserController::class, 'destroy']);
// 查询列表接口
Route::post('adsense/query', [AdsenseController::class, 'query']);
// 新增接口
Route::post('adsense/store', [AdsenseController::class, 'store']);
// 获取详情接口
Route::get('adsense/show', [AdsenseController::class, 'show'])->name('adsense.show');
// 更新接口
Route::put('adsense/update', [AdsenseController::class, 'update']);
// 删除接口
Route::delete('adsense/destroy', [AdsenseController::class, 'destroy']);
// 查询列表接口
Route::post('affiliateLog/query', [AffiliateLogController::class, 'query']);
// 新增接口
Route::post('affiliateLog/store', [AffiliateLogController::class, 'store']);
// 获取详情接口
Route::get('affiliateLog/show', [AffiliateLogController::class, 'show'])->name('affiliateLog.show');
// 更新接口
Route::put('affiliateLog/update', [AffiliateLogController::class, 'update']);
// 删除接口
Route::delete('affiliateLog/destroy', [AffiliateLogController::class, 'destroy']);
// 查询列表接口
Route::post('agency/query', [AgencyController::class, 'query']);
// 新增接口
Route::post('agency/store', [AgencyController::class, 'store']);
// 获取详情接口
Route::get('agency/show', [AgencyController::class, 'show'])->name('agency.show');
// 更新接口
Route::put('agency/update', [AgencyController::class, 'update']);
// 删除接口
Route::delete('agency/destroy', [AgencyController::class, 'destroy']);
// 查询列表接口
Route::post('areaRegion/query', [AreaRegionController::class, 'query']);
// 新增接口
Route::post('areaRegion/store', [AreaRegionController::class, 'store']);
// 获取详情接口
Route::get('areaRegion/show', [AreaRegionController::class, 'show'])->name('areaRegion.show');
// 更新接口
Route::put('areaRegion/update', [AreaRegionController::class, 'update']);
// 删除接口
Route::delete('areaRegion/destroy', [AreaRegionController::class, 'destroy']);
// 查询列表接口
Route::post('articleCat/query', [ArticleCatController::class, 'query']);
// 新增接口
Route::post('articleCat/store', [ArticleCatController::class, 'store']);
// 获取详情接口
Route::get('articleCat/show', [ArticleCatController::class, 'show'])->name('articleCat.show');
// 更新接口
Route::put('articleCat/update', [ArticleCatController::class, 'update']);
// 删除接口
Route::delete('articleCat/destroy', [ArticleCatController::class, 'destroy']);
// 查询列表接口
Route::post('article/query', [ArticleController::class, 'query']);
// 新增接口
Route::post('article/store', [ArticleController::class, 'store']);
// 获取详情接口
Route::get('article/show', [ArticleController::class, 'show'])->name('article.show');
// 更新接口
Route::put('article/update', [ArticleController::class, 'update']);
// 删除接口
Route::delete('article/destroy', [ArticleController::class, 'destroy']);
// 查询列表接口
Route::post('attribute/query', [AttributeController::class, 'query']);
// 新增接口
Route::post('attribute/store', [AttributeController::class, 'store']);
// 获取详情接口
Route::get('attribute/show', [AttributeController::class, 'show'])->name('attribute.show');
// 更新接口
Route::put('attribute/update', [AttributeController::class, 'update']);
// 删除接口
Route::delete('attribute/destroy', [AttributeController::class, 'destroy']);
// 查询列表接口
Route::post('auctionLog/query', [AuctionLogController::class, 'query']);
// 新增接口
Route::post('auctionLog/store', [AuctionLogController::class, 'store']);
// 获取详情接口
Route::get('auctionLog/show', [AuctionLogController::class, 'show'])->name('auctionLog.show');
// 更新接口
Route::put('auctionLog/update', [AuctionLogController::class, 'update']);
// 删除接口
Route::delete('auctionLog/destroy', [AuctionLogController::class, 'destroy']);
// 查询列表接口
Route::post('autoManage/query', [AutoManageController::class, 'query']);
// 新增接口
Route::post('autoManage/store', [AutoManageController::class, 'store']);
// 获取详情接口
Route::get('autoManage/show', [AutoManageController::class, 'show'])->name('autoManage.show');
// 更新接口
Route::put('autoManage/update', [AutoManageController::class, 'update']);
// 删除接口
Route::delete('autoManage/destroy', [AutoManageController::class, 'destroy']);
// 查询列表接口
Route::post('backGoods/query', [BackGoodsController::class, 'query']);
// 新增接口
Route::post('backGoods/store', [BackGoodsController::class, 'store']);
// 获取详情接口
Route::get('backGoods/show', [BackGoodsController::class, 'show'])->name('backGoods.show');
// 更新接口
Route::put('backGoods/update', [BackGoodsController::class, 'update']);
// 删除接口
Route::delete('backGoods/destroy', [BackGoodsController::class, 'destroy']);
// 查询列表接口
Route::post('backOrder/query', [BackOrderController::class, 'query']);
// 新增接口
Route::post('backOrder/store', [BackOrderController::class, 'store']);
// 获取详情接口
Route::get('backOrder/show', [BackOrderController::class, 'show'])->name('backOrder.show');
// 更新接口
Route::put('backOrder/update', [BackOrderController::class, 'update']);
// 删除接口
Route::delete('backOrder/destroy', [BackOrderController::class, 'destroy']);
// 查询列表接口
Route::post('bonusType/query', [BonusTypeController::class, 'query']);
// 新增接口
Route::post('bonusType/store', [BonusTypeController::class, 'store']);
// 获取详情接口
Route::get('bonusType/show', [BonusTypeController::class, 'show'])->name('bonusType.show');
// 更新接口
Route::put('bonusType/update', [BonusTypeController::class, 'update']);
// 删除接口
Route::delete('bonusType/destroy', [BonusTypeController::class, 'destroy']);
// 查询列表接口
Route::post('bookingGoods/query', [BookingGoodsController::class, 'query']);
// 新增接口
Route::post('bookingGoods/store', [BookingGoodsController::class, 'store']);
// 获取详情接口
Route::get('bookingGoods/show', [BookingGoodsController::class, 'show'])->name('bookingGoods.show');
// 更新接口
Route::put('bookingGoods/update', [BookingGoodsController::class, 'update']);
// 删除接口
Route::delete('bookingGoods/destroy', [BookingGoodsController::class, 'destroy']);
// 查询列表接口
Route::post('brand/query', [BrandController::class, 'query']);
// 新增接口
Route::post('brand/store', [BrandController::class, 'store']);
// 获取详情接口
Route::get('brand/show', [BrandController::class, 'show'])->name('brand.show');
// 更新接口
Route::put('brand/update', [BrandController::class, 'update']);
// 删除接口
Route::delete('brand/destroy', [BrandController::class, 'destroy']);
// 查询列表接口
Route::post('card/query', [CardController::class, 'query']);
// 新增接口
Route::post('card/store', [CardController::class, 'store']);
// 获取详情接口
Route::get('card/show', [CardController::class, 'show'])->name('card.show');
// 更新接口
Route::put('card/update', [CardController::class, 'update']);
// 删除接口
Route::delete('card/destroy', [CardController::class, 'destroy']);
// 查询列表接口
Route::post('cart/query', [CartController::class, 'query']);
// 新增接口
Route::post('cart/store', [CartController::class, 'store']);
// 获取详情接口
Route::get('cart/show', [CartController::class, 'show'])->name('cart.show');
// 更新接口
Route::put('cart/update', [CartController::class, 'update']);
// 删除接口
Route::delete('cart/destroy', [CartController::class, 'destroy']);
// 查询列表接口
Route::post('catRecommend/query', [CatRecommendController::class, 'query']);
// 新增接口
Route::post('catRecommend/store', [CatRecommendController::class, 'store']);
// 获取详情接口
Route::get('catRecommend/show', [CatRecommendController::class, 'show'])->name('catRecommend.show');
// 更新接口
Route::put('catRecommend/update', [CatRecommendController::class, 'update']);
// 删除接口
Route::delete('catRecommend/destroy', [CatRecommendController::class, 'destroy']);
// 查询列表接口
Route::post('category/query', [CategoryController::class, 'query']);
// 新增接口
Route::post('category/store', [CategoryController::class, 'store']);
// 获取详情接口
Route::get('category/show', [CategoryController::class, 'show'])->name('category.show');
// 更新接口
Route::put('category/update', [CategoryController::class, 'update']);
// 删除接口
Route::delete('category/destroy', [CategoryController::class, 'destroy']);
// 查询列表接口
Route::post('collectGoods/query', [CollectGoodsController::class, 'query']);
// 新增接口
Route::post('collectGoods/store', [CollectGoodsController::class, 'store']);
// 获取详情接口
Route::get('collectGoods/show', [CollectGoodsController::class, 'show'])->name('collectGoods.show');
// 更新接口
Route::put('collectGoods/update', [CollectGoodsController::class, 'update']);
// 删除接口
Route::delete('collectGoods/destroy', [CollectGoodsController::class, 'destroy']);
// 查询列表接口
Route::post('comment/query', [CommentController::class, 'query']);
// 新增接口
Route::post('comment/store', [CommentController::class, 'store']);
// 获取详情接口
Route::get('comment/show', [CommentController::class, 'show'])->name('comment.show');
// 更新接口
Route::put('comment/update', [CommentController::class, 'update']);
// 删除接口
Route::delete('comment/destroy', [CommentController::class, 'destroy']);
// 查询列表接口
Route::post('crons/query', [CronsController::class, 'query']);
// 新增接口
Route::post('crons/store', [CronsController::class, 'store']);
// 获取详情接口
Route::get('crons/show', [CronsController::class, 'show'])->name('crons.show');
// 更新接口
Route::put('crons/update', [CronsController::class, 'update']);
// 删除接口
Route::delete('crons/destroy', [CronsController::class, 'destroy']);
// 查询列表接口
Route::post('deliveryGoods/query', [DeliveryGoodsController::class, 'query']);
// 新增接口
Route::post('deliveryGoods/store', [DeliveryGoodsController::class, 'store']);
// 获取详情接口
Route::get('deliveryGoods/show', [DeliveryGoodsController::class, 'show'])->name('deliveryGoods.show');
// 更新接口
Route::put('deliveryGoods/update', [DeliveryGoodsController::class, 'update']);
// 删除接口
Route::delete('deliveryGoods/destroy', [DeliveryGoodsController::class, 'destroy']);
// 查询列表接口
Route::post('deliveryOrder/query', [DeliveryOrderController::class, 'query']);
// 新增接口
Route::post('deliveryOrder/store', [DeliveryOrderController::class, 'store']);
// 获取详情接口
Route::get('deliveryOrder/show', [DeliveryOrderController::class, 'show'])->name('deliveryOrder.show');
// 更新接口
Route::put('deliveryOrder/update', [DeliveryOrderController::class, 'update']);
// 删除接口
Route::delete('deliveryOrder/destroy', [DeliveryOrderController::class, 'destroy']);
// 查询列表接口
Route::post('emailList/query', [EmailListController::class, 'query']);
// 新增接口
Route::post('emailList/store', [EmailListController::class, 'store']);
// 获取详情接口
Route::get('emailList/show', [EmailListController::class, 'show'])->name('emailList.show');
// 更新接口
Route::put('emailList/update', [EmailListController::class, 'update']);
// 删除接口
Route::delete('emailList/destroy', [EmailListController::class, 'destroy']);
// 查询列表接口
Route::post('emailSendlist/query', [EmailSendlistController::class, 'query']);
// 新增接口
Route::post('emailSendlist/store', [EmailSendlistController::class, 'store']);
// 获取详情接口
Route::get('emailSendlist/show', [EmailSendlistController::class, 'show'])->name('emailSendlist.show');
// 更新接口
Route::put('emailSendlist/update', [EmailSendlistController::class, 'update']);
// 删除接口
Route::delete('emailSendlist/destroy', [EmailSendlistController::class, 'destroy']);
// 查询列表接口
Route::post('errorLog/query', [ErrorLogController::class, 'query']);
// 新增接口
Route::post('errorLog/store', [ErrorLogController::class, 'store']);
// 获取详情接口
Route::get('errorLog/show', [ErrorLogController::class, 'show'])->name('errorLog.show');
// 更新接口
Route::put('errorLog/update', [ErrorLogController::class, 'update']);
// 删除接口
Route::delete('errorLog/destroy', [ErrorLogController::class, 'destroy']);
// 查询列表接口
Route::post('exchangeGoods/query', [ExchangeGoodsController::class, 'query']);
// 新增接口
Route::post('exchangeGoods/store', [ExchangeGoodsController::class, 'store']);
// 获取详情接口
Route::get('exchangeGoods/show', [ExchangeGoodsController::class, 'show'])->name('exchangeGoods.show');
// 更新接口
Route::put('exchangeGoods/update', [ExchangeGoodsController::class, 'update']);
// 删除接口
Route::delete('exchangeGoods/destroy', [ExchangeGoodsController::class, 'destroy']);
// 查询列表接口
Route::post('favourableActivity/query', [FavourableActivityController::class, 'query']);
// 新增接口
Route::post('favourableActivity/store', [FavourableActivityController::class, 'store']);
// 获取详情接口
Route::get('favourableActivity/show', [FavourableActivityController::class, 'show'])->name('favourableActivity.show');
// 更新接口
Route::put('favourableActivity/update', [FavourableActivityController::class, 'update']);
// 删除接口
Route::delete('favourableActivity/destroy', [FavourableActivityController::class, 'destroy']);
// 查询列表接口
Route::post('feedback/query', [FeedbackController::class, 'query']);
// 新增接口
Route::post('feedback/store', [FeedbackController::class, 'store']);
// 获取详情接口
Route::get('feedback/show', [FeedbackController::class, 'show'])->name('feedback.show');
// 更新接口
Route::put('feedback/update', [FeedbackController::class, 'update']);
// 删除接口
Route::delete('feedback/destroy', [FeedbackController::class, 'destroy']);
// 查询列表接口
Route::post('friendLink/query', [FriendLinkController::class, 'query']);
// 新增接口
Route::post('friendLink/store', [FriendLinkController::class, 'store']);
// 获取详情接口
Route::get('friendLink/show', [FriendLinkController::class, 'show'])->name('friendLink.show');
// 更新接口
Route::put('friendLink/update', [FriendLinkController::class, 'update']);
// 删除接口
Route::delete('friendLink/destroy', [FriendLinkController::class, 'destroy']);
// 查询列表接口
Route::post('goodsActivity/query', [GoodsActivityController::class, 'query']);
// 新增接口
Route::post('goodsActivity/store', [GoodsActivityController::class, 'store']);
// 获取详情接口
Route::get('goodsActivity/show', [GoodsActivityController::class, 'show'])->name('goodsActivity.show');
// 更新接口
Route::put('goodsActivity/update', [GoodsActivityController::class, 'update']);
// 删除接口
Route::delete('goodsActivity/destroy', [GoodsActivityController::class, 'destroy']);
// 查询列表接口
Route::post('goodsArticle/query', [GoodsArticleController::class, 'query']);
// 新增接口
Route::post('goodsArticle/store', [GoodsArticleController::class, 'store']);
// 获取详情接口
Route::get('goodsArticle/show', [GoodsArticleController::class, 'show'])->name('goodsArticle.show');
// 更新接口
Route::put('goodsArticle/update', [GoodsArticleController::class, 'update']);
// 删除接口
Route::delete('goodsArticle/destroy', [GoodsArticleController::class, 'destroy']);
// 查询列表接口
Route::post('goodsAttr/query', [GoodsAttrController::class, 'query']);
// 新增接口
Route::post('goodsAttr/store', [GoodsAttrController::class, 'store']);
// 获取详情接口
Route::get('goodsAttr/show', [GoodsAttrController::class, 'show'])->name('goodsAttr.show');
// 更新接口
Route::put('goodsAttr/update', [GoodsAttrController::class, 'update']);
// 删除接口
Route::delete('goodsAttr/destroy', [GoodsAttrController::class, 'destroy']);
// 查询列表接口
Route::post('goodsCat/query', [GoodsCatController::class, 'query']);
// 新增接口
Route::post('goodsCat/store', [GoodsCatController::class, 'store']);
// 获取详情接口
Route::get('goodsCat/show', [GoodsCatController::class, 'show'])->name('goodsCat.show');
// 更新接口
Route::put('goodsCat/update', [GoodsCatController::class, 'update']);
// 删除接口
Route::delete('goodsCat/destroy', [GoodsCatController::class, 'destroy']);
// 查询列表接口
Route::post('goods/query', [GoodsController::class, 'query']);
// 新增接口
Route::post('goods/store', [GoodsController::class, 'store']);
// 获取详情接口
Route::get('goods/show', [GoodsController::class, 'show'])->name('goods.show');
// 更新接口
Route::put('goods/update', [GoodsController::class, 'update']);
// 删除接口
Route::delete('goods/destroy', [GoodsController::class, 'destroy']);
// 查询列表接口
Route::post('goodsGallery/query', [GoodsGalleryController::class, 'query']);
// 新增接口
Route::post('goodsGallery/store', [GoodsGalleryController::class, 'store']);
// 获取详情接口
Route::get('goodsGallery/show', [GoodsGalleryController::class, 'show'])->name('goodsGallery.show');
// 更新接口
Route::put('goodsGallery/update', [GoodsGalleryController::class, 'update']);
// 删除接口
Route::delete('goodsGallery/destroy', [GoodsGalleryController::class, 'destroy']);
// 查询列表接口
Route::post('goodsType/query', [GoodsTypeController::class, 'query']);
// 新增接口
Route::post('goodsType/store', [GoodsTypeController::class, 'store']);
// 获取详情接口
Route::get('goodsType/show', [GoodsTypeController::class, 'show'])->name('goodsType.show');
// 更新接口
Route::put('goodsType/update', [GoodsTypeController::class, 'update']);
// 删除接口
Route::delete('goodsType/destroy', [GoodsTypeController::class, 'destroy']);
// 查询列表接口
Route::post('groupGoods/query', [GroupGoodsController::class, 'query']);
// 新增接口
Route::post('groupGoods/store', [GroupGoodsController::class, 'store']);
// 获取详情接口
Route::get('groupGoods/show', [GroupGoodsController::class, 'show'])->name('groupGoods.show');
// 更新接口
Route::put('groupGoods/update', [GroupGoodsController::class, 'update']);
// 删除接口
Route::delete('groupGoods/destroy', [GroupGoodsController::class, 'destroy']);
// 查询列表接口
Route::post('keywords/query', [KeywordsController::class, 'query']);
// 新增接口
Route::post('keywords/store', [KeywordsController::class, 'store']);
// 获取详情接口
Route::get('keywords/show', [KeywordsController::class, 'show'])->name('keywords.show');
// 更新接口
Route::put('keywords/update', [KeywordsController::class, 'update']);
// 删除接口
Route::delete('keywords/destroy', [KeywordsController::class, 'destroy']);
// 查询列表接口
Route::post('linkGoods/query', [LinkGoodsController::class, 'query']);
// 新增接口
Route::post('linkGoods/store', [LinkGoodsController::class, 'store']);
// 获取详情接口
Route::get('linkGoods/show', [LinkGoodsController::class, 'show'])->name('linkGoods.show');
// 更新接口
Route::put('linkGoods/update', [LinkGoodsController::class, 'update']);
// 删除接口
Route::delete('linkGoods/destroy', [LinkGoodsController::class, 'destroy']);
// 查询列表接口
Route::post('mailTemplates/query', [MailTemplatesController::class, 'query']);
// 新增接口
Route::post('mailTemplates/store', [MailTemplatesController::class, 'store']);
// 获取详情接口
Route::get('mailTemplates/show', [MailTemplatesController::class, 'show'])->name('mailTemplates.show');
// 更新接口
Route::put('mailTemplates/update', [MailTemplatesController::class, 'update']);
// 删除接口
Route::delete('mailTemplates/destroy', [MailTemplatesController::class, 'destroy']);
// 查询列表接口
Route::post('memberPrice/query', [MemberPriceController::class, 'query']);
// 新增接口
Route::post('memberPrice/store', [MemberPriceController::class, 'store']);
// 获取详情接口
Route::get('memberPrice/show', [MemberPriceController::class, 'show'])->name('memberPrice.show');
// 更新接口
Route::put('memberPrice/update', [MemberPriceController::class, 'update']);
// 删除接口
Route::delete('memberPrice/destroy', [MemberPriceController::class, 'destroy']);
// 查询列表接口
Route::post('nav/query', [NavController::class, 'query']);
// 新增接口
Route::post('nav/store', [NavController::class, 'store']);
// 获取详情接口
Route::get('nav/show', [NavController::class, 'show'])->name('nav.show');
// 更新接口
Route::put('nav/update', [NavController::class, 'update']);
// 删除接口
Route::delete('nav/destroy', [NavController::class, 'destroy']);
// 查询列表接口
Route::post('orderAction/query', [OrderActionController::class, 'query']);
// 新增接口
Route::post('orderAction/store', [OrderActionController::class, 'store']);
// 获取详情接口
Route::get('orderAction/show', [OrderActionController::class, 'show'])->name('orderAction.show');
// 更新接口
Route::put('orderAction/update', [OrderActionController::class, 'update']);
// 删除接口
Route::delete('orderAction/destroy', [OrderActionController::class, 'destroy']);
// 查询列表接口
Route::post('orderGoods/query', [OrderGoodsController::class, 'query']);
// 新增接口
Route::post('orderGoods/store', [OrderGoodsController::class, 'store']);
// 获取详情接口
Route::get('orderGoods/show', [OrderGoodsController::class, 'show'])->name('orderGoods.show');
// 更新接口
Route::put('orderGoods/update', [OrderGoodsController::class, 'update']);
// 删除接口
Route::delete('orderGoods/destroy', [OrderGoodsController::class, 'destroy']);
// 查询列表接口
Route::post('orderInfo/query', [OrderInfoController::class, 'query']);
// 新增接口
Route::post('orderInfo/store', [OrderInfoController::class, 'store']);
// 获取详情接口
Route::get('orderInfo/show', [OrderInfoController::class, 'show'])->name('orderInfo.show');
// 更新接口
Route::put('orderInfo/update', [OrderInfoController::class, 'update']);
// 删除接口
Route::delete('orderInfo/destroy', [OrderInfoController::class, 'destroy']);
// 查询列表接口
Route::post('pack/query', [PackController::class, 'query']);
// 新增接口
Route::post('pack/store', [PackController::class, 'store']);
// 获取详情接口
Route::get('pack/show', [PackController::class, 'show'])->name('pack.show');
// 更新接口
Route::put('pack/update', [PackController::class, 'update']);
// 删除接口
Route::delete('pack/destroy', [PackController::class, 'destroy']);
// 查询列表接口
Route::post('packageGoods/query', [PackageGoodsController::class, 'query']);
// 新增接口
Route::post('packageGoods/store', [PackageGoodsController::class, 'store']);
// 获取详情接口
Route::get('packageGoods/show', [PackageGoodsController::class, 'show'])->name('packageGoods.show');
// 更新接口
Route::put('packageGoods/update', [PackageGoodsController::class, 'update']);
// 删除接口
Route::delete('packageGoods/destroy', [PackageGoodsController::class, 'destroy']);
// 查询列表接口
Route::post('payLog/query', [PayLogController::class, 'query']);
// 新增接口
Route::post('payLog/store', [PayLogController::class, 'store']);
// 获取详情接口
Route::get('payLog/show', [PayLogController::class, 'show'])->name('payLog.show');
// 更新接口
Route::put('payLog/update', [PayLogController::class, 'update']);
// 删除接口
Route::delete('payLog/destroy', [PayLogController::class, 'destroy']);
// 查询列表接口
Route::post('payment/query', [PaymentController::class, 'query']);
// 新增接口
Route::post('payment/store', [PaymentController::class, 'store']);
// 获取详情接口
Route::get('payment/show', [PaymentController::class, 'show'])->name('payment.show');
// 更新接口
Route::put('payment/update', [PaymentController::class, 'update']);
// 删除接口
Route::delete('payment/destroy', [PaymentController::class, 'destroy']);
// 查询列表接口
Route::post('plugins/query', [PluginsController::class, 'query']);
// 新增接口
Route::post('plugins/store', [PluginsController::class, 'store']);
// 获取详情接口
Route::get('plugins/show', [PluginsController::class, 'show'])->name('plugins.show');
// 更新接口
Route::put('plugins/update', [PluginsController::class, 'update']);
// 删除接口
Route::delete('plugins/destroy', [PluginsController::class, 'destroy']);
// 查询列表接口
Route::post('products/query', [ProductsController::class, 'query']);
// 新增接口
Route::post('products/store', [ProductsController::class, 'store']);
// 获取详情接口
Route::get('products/show', [ProductsController::class, 'show'])->name('products.show');
// 更新接口
Route::put('products/update', [ProductsController::class, 'update']);
// 删除接口
Route::delete('products/destroy', [ProductsController::class, 'destroy']);
// 查询列表接口
Route::post('regExtendInfo/query', [RegExtendInfoController::class, 'query']);
// 新增接口
Route::post('regExtendInfo/store', [RegExtendInfoController::class, 'store']);
// 获取详情接口
Route::get('regExtendInfo/show', [RegExtendInfoController::class, 'show'])->name('regExtendInfo.show');
// 更新接口
Route::put('regExtendInfo/update', [RegExtendInfoController::class, 'update']);
// 删除接口
Route::delete('regExtendInfo/destroy', [RegExtendInfoController::class, 'destroy']);
// 查询列表接口
Route::post('regFields/query', [RegFieldsController::class, 'query']);
// 新增接口
Route::post('regFields/store', [RegFieldsController::class, 'store']);
// 获取详情接口
Route::get('regFields/show', [RegFieldsController::class, 'show'])->name('regFields.show');
// 更新接口
Route::put('regFields/update', [RegFieldsController::class, 'update']);
// 删除接口
Route::delete('regFields/destroy', [RegFieldsController::class, 'destroy']);
// 查询列表接口
Route::post('region/query', [RegionController::class, 'query']);
// 新增接口
Route::post('region/store', [RegionController::class, 'store']);
// 获取详情接口
Route::get('region/show', [RegionController::class, 'show'])->name('region.show');
// 更新接口
Route::put('region/update', [RegionController::class, 'update']);
// 删除接口
Route::delete('region/destroy', [RegionController::class, 'destroy']);
// 查询列表接口
Route::post('role/query', [RoleController::class, 'query']);
// 新增接口
Route::post('role/store', [RoleController::class, 'store']);
// 获取详情接口
Route::get('role/show', [RoleController::class, 'show'])->name('role.show');
// 更新接口
Route::put('role/update', [RoleController::class, 'update']);
// 删除接口
Route::delete('role/destroy', [RoleController::class, 'destroy']);
// 查询列表接口
Route::post('searchengine/query', [SearchengineController::class, 'query']);
// 新增接口
Route::post('searchengine/store', [SearchengineController::class, 'store']);
// 获取详情接口
Route::get('searchengine/show', [SearchengineController::class, 'show'])->name('searchengine.show');
// 更新接口
Route::put('searchengine/update', [SearchengineController::class, 'update']);
// 删除接口
Route::delete('searchengine/destroy', [SearchengineController::class, 'destroy']);
// 查询列表接口
Route::post('shippingArea/query', [ShippingAreaController::class, 'query']);
// 新增接口
Route::post('shippingArea/store', [ShippingAreaController::class, 'store']);
// 获取详情接口
Route::get('shippingArea/show', [ShippingAreaController::class, 'show'])->name('shippingArea.show');
// 更新接口
Route::put('shippingArea/update', [ShippingAreaController::class, 'update']);
// 删除接口
Route::delete('shippingArea/destroy', [ShippingAreaController::class, 'destroy']);
// 查询列表接口
Route::post('shipping/query', [ShippingController::class, 'query']);
// 新增接口
Route::post('shipping/store', [ShippingController::class, 'store']);
// 获取详情接口
Route::get('shipping/show', [ShippingController::class, 'show'])->name('shipping.show');
// 更新接口
Route::put('shipping/update', [ShippingController::class, 'update']);
// 删除接口
Route::delete('shipping/destroy', [ShippingController::class, 'destroy']);
// 查询列表接口
Route::post('shopConfig/query', [ShopConfigController::class, 'query']);
// 新增接口
Route::post('shopConfig/store', [ShopConfigController::class, 'store']);
// 获取详情接口
Route::get('shopConfig/show', [ShopConfigController::class, 'show'])->name('shopConfig.show');
// 更新接口
Route::put('shopConfig/update', [ShopConfigController::class, 'update']);
// 删除接口
Route::delete('shopConfig/destroy', [ShopConfigController::class, 'destroy']);
// 查询列表接口
Route::post('snatchLog/query', [SnatchLogController::class, 'query']);
// 新增接口
Route::post('snatchLog/store', [SnatchLogController::class, 'store']);
// 获取详情接口
Route::get('snatchLog/show', [SnatchLogController::class, 'show'])->name('snatchLog.show');
// 更新接口
Route::put('snatchLog/update', [SnatchLogController::class, 'update']);
// 删除接口
Route::delete('snatchLog/destroy', [SnatchLogController::class, 'destroy']);
// 查询列表接口
Route::post('stats/query', [StatsController::class, 'query']);
// 新增接口
Route::post('stats/store', [StatsController::class, 'store']);
// 获取详情接口
Route::get('stats/show', [StatsController::class, 'show'])->name('stats.show');
// 更新接口
Route::put('stats/update', [StatsController::class, 'update']);
// 删除接口
Route::delete('stats/destroy', [StatsController::class, 'destroy']);
// 查询列表接口
Route::post('suppliers/query', [SuppliersController::class, 'query']);
// 新增接口
Route::post('suppliers/store', [SuppliersController::class, 'store']);
// 获取详情接口
Route::get('suppliers/show', [SuppliersController::class, 'show'])->name('suppliers.show');
// 更新接口
Route::put('suppliers/update', [SuppliersController::class, 'update']);
// 删除接口
Route::delete('suppliers/destroy', [SuppliersController::class, 'destroy']);
// 查询列表接口
Route::post('tag/query', [TagController::class, 'query']);
// 新增接口
Route::post('tag/store', [TagController::class, 'store']);
// 获取详情接口
Route::get('tag/show', [TagController::class, 'show'])->name('tag.show');
// 更新接口
Route::put('tag/update', [TagController::class, 'update']);
// 删除接口
Route::delete('tag/destroy', [TagController::class, 'destroy']);
// 查询列表接口
Route::post('template/query', [TemplateController::class, 'query']);
// 新增接口
Route::post('template/store', [TemplateController::class, 'store']);
// 获取详情接口
Route::get('template/show', [TemplateController::class, 'show'])->name('template.show');
// 更新接口
Route::put('template/update', [TemplateController::class, 'update']);
// 删除接口
Route::delete('template/destroy', [TemplateController::class, 'destroy']);
// 查询列表接口
Route::post('topic/query', [TopicController::class, 'query']);
// 新增接口
Route::post('topic/store', [TopicController::class, 'store']);
// 获取详情接口
Route::get('topic/show', [TopicController::class, 'show'])->name('topic.show');
// 更新接口
Route::put('topic/update', [TopicController::class, 'update']);
// 删除接口
Route::delete('topic/destroy', [TopicController::class, 'destroy']);
// 查询列表接口
Route::post('userAccount/query', [UserAccountController::class, 'query']);
// 新增接口
Route::post('userAccount/store', [UserAccountController::class, 'store']);
// 获取详情接口
Route::get('userAccount/show', [UserAccountController::class, 'show'])->name('userAccount.show');
// 更新接口
Route::put('userAccount/update', [UserAccountController::class, 'update']);
// 删除接口
Route::delete('userAccount/destroy', [UserAccountController::class, 'destroy']);
// 查询列表接口
Route::post('userAddress/query', [UserAddressController::class, 'query']);
// 新增接口
Route::post('userAddress/store', [UserAddressController::class, 'store']);
// 获取详情接口
Route::get('userAddress/show', [UserAddressController::class, 'show'])->name('userAddress.show');
// 更新接口
Route::put('userAddress/update', [UserAddressController::class, 'update']);
// 删除接口
Route::delete('userAddress/destroy', [UserAddressController::class, 'destroy']);
// 查询列表接口
Route::post('userBonus/query', [UserBonusController::class, 'query']);
// 新增接口
Route::post('userBonus/store', [UserBonusController::class, 'store']);
// 获取详情接口
Route::get('userBonus/show', [UserBonusController::class, 'show'])->name('userBonus.show');
// 更新接口
Route::put('userBonus/update', [UserBonusController::class, 'update']);
// 删除接口
Route::delete('userBonus/destroy', [UserBonusController::class, 'destroy']);
// 查询列表接口
Route::post('userFeed/query', [UserFeedController::class, 'query']);
// 新增接口
Route::post('userFeed/store', [UserFeedController::class, 'store']);
// 获取详情接口
Route::get('userFeed/show', [UserFeedController::class, 'show'])->name('userFeed.show');
// 更新接口
Route::put('userFeed/update', [UserFeedController::class, 'update']);
// 删除接口
Route::delete('userFeed/destroy', [UserFeedController::class, 'destroy']);
// 查询列表接口
Route::post('userRank/query', [UserRankController::class, 'query']);
// 新增接口
Route::post('userRank/store', [UserRankController::class, 'store']);
// 获取详情接口
Route::get('userRank/show', [UserRankController::class, 'show'])->name('userRank.show');
// 更新接口
Route::put('userRank/update', [UserRankController::class, 'update']);
// 删除接口
Route::delete('userRank/destroy', [UserRankController::class, 'destroy']);
// 查询列表接口
Route::post('users/query', [UsersController::class, 'query']);
// 新增接口
Route::post('users/store', [UsersController::class, 'store']);
// 获取详情接口
Route::get('users/show', [UsersController::class, 'show'])->name('users.show');
// 更新接口
Route::put('users/update', [UsersController::class, 'update']);
// 删除接口
Route::delete('users/destroy', [UsersController::class, 'destroy']);
// 查询列表接口
Route::post('virtualCard/query', [VirtualCardController::class, 'query']);
// 新增接口
Route::post('virtualCard/store', [VirtualCardController::class, 'store']);
// 获取详情接口
Route::get('virtualCard/show', [VirtualCardController::class, 'show'])->name('virtualCard.show');
// 更新接口
Route::put('virtualCard/update', [VirtualCardController::class, 'update']);
// 删除接口
Route::delete('virtualCard/destroy', [VirtualCardController::class, 'destroy']);
// 查询列表接口
Route::post('volumePrice/query', [VolumePriceController::class, 'query']);
// 新增接口
Route::post('volumePrice/store', [VolumePriceController::class, 'store']);
// 获取详情接口
Route::get('volumePrice/show', [VolumePriceController::class, 'show'])->name('volumePrice.show');
// 更新接口
Route::put('volumePrice/update', [VolumePriceController::class, 'update']);
// 删除接口
Route::delete('volumePrice/destroy', [VolumePriceController::class, 'destroy']);
// 查询列表接口
Route::post('vote/query', [VoteController::class, 'query']);
// 新增接口
Route::post('vote/store', [VoteController::class, 'store']);
// 获取详情接口
Route::get('vote/show', [VoteController::class, 'show'])->name('vote.show');
// 更新接口
Route::put('vote/update', [VoteController::class, 'update']);
// 删除接口
Route::delete('vote/destroy', [VoteController::class, 'destroy']);
// 查询列表接口
Route::post('voteLog/query', [VoteLogController::class, 'query']);
// 新增接口
Route::post('voteLog/store', [VoteLogController::class, 'store']);
// 获取详情接口
Route::get('voteLog/show', [VoteLogController::class, 'show'])->name('voteLog.show');
// 更新接口
Route::put('voteLog/update', [VoteLogController::class, 'update']);
// 删除接口
Route::delete('voteLog/destroy', [VoteLogController::class, 'destroy']);
// 查询列表接口
Route::post('voteOption/query', [VoteOptionController::class, 'query']);
// 新增接口
Route::post('voteOption/store', [VoteOptionController::class, 'store']);
// 获取详情接口
Route::get('voteOption/show', [VoteOptionController::class, 'show'])->name('voteOption.show');
// 更新接口
Route::put('voteOption/update', [VoteOptionController::class, 'update']);
// 删除接口
Route::delete('voteOption/destroy', [VoteOptionController::class, 'destroy']);
// 查询列表接口
Route::post('wholesale/query', [WholesaleController::class, 'query']);
// 新增接口
Route::post('wholesale/store', [WholesaleController::class, 'store']);
// 获取详情接口
Route::get('wholesale/show', [WholesaleController::class, 'show'])->name('wholesale.show');
// 更新接口
Route::put('wholesale/update', [WholesaleController::class, 'update']);
// 删除接口
Route::delete('wholesale/destroy', [WholesaleController::class, 'destroy']);
