<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// Route start
Route::prefix('admin')->group(function () {
    // 查询列表接口
    Route::post('accountLog/query', [\App\Api\Admin\Controllers\AccountLogController::class, 'query']);
    // 新增接口
    Route::post('accountLog/store', [\App\Api\Admin\Controllers\AccountLogController::class, 'store']);
    // 获取详情接口
    Route::get('accountLog/show', [\App\Api\Admin\Controllers\AccountLogController::class, 'show']);
    // 更新接口
    Route::put('accountLog/update', [\App\Api\Admin\Controllers\AccountLogController::class, 'update']);
    // 删除接口
    Route::delete('accountLog/destroy', [\App\Api\Admin\Controllers\AccountLogController::class, 'destroy']);
    // 查询列表接口
    Route::post('ad/query', [\App\Api\Admin\Controllers\AdController::class, 'query']);
    // 新增接口
    Route::post('ad/store', [\App\Api\Admin\Controllers\AdController::class, 'store']);
    // 获取详情接口
    Route::get('ad/show', [\App\Api\Admin\Controllers\AdController::class, 'show']);
    // 更新接口
    Route::put('ad/update', [\App\Api\Admin\Controllers\AdController::class, 'update']);
    // 删除接口
    Route::delete('ad/destroy', [\App\Api\Admin\Controllers\AdController::class, 'destroy']);
    // 查询列表接口
    Route::post('adCustom/query', [\App\Api\Admin\Controllers\AdCustomController::class, 'query']);
    // 新增接口
    Route::post('adCustom/store', [\App\Api\Admin\Controllers\AdCustomController::class, 'store']);
    // 获取详情接口
    Route::get('adCustom/show', [\App\Api\Admin\Controllers\AdCustomController::class, 'show']);
    // 更新接口
    Route::put('adCustom/update', [\App\Api\Admin\Controllers\AdCustomController::class, 'update']);
    // 删除接口
    Route::delete('adCustom/destroy', [\App\Api\Admin\Controllers\AdCustomController::class, 'destroy']);
    // 查询列表接口
    Route::post('adPosition/query', [\App\Api\Admin\Controllers\AdPositionController::class, 'query']);
    // 新增接口
    Route::post('adPosition/store', [\App\Api\Admin\Controllers\AdPositionController::class, 'store']);
    // 获取详情接口
    Route::get('adPosition/show', [\App\Api\Admin\Controllers\AdPositionController::class, 'show']);
    // 更新接口
    Route::put('adPosition/update', [\App\Api\Admin\Controllers\AdPositionController::class, 'update']);
    // 删除接口
    Route::delete('adPosition/destroy', [\App\Api\Admin\Controllers\AdPositionController::class, 'destroy']);
    // 查询列表接口
    Route::post('adminAction/query', [\App\Api\Admin\Controllers\AdminActionController::class, 'query']);
    // 新增接口
    Route::post('adminAction/store', [\App\Api\Admin\Controllers\AdminActionController::class, 'store']);
    // 获取详情接口
    Route::get('adminAction/show', [\App\Api\Admin\Controllers\AdminActionController::class, 'show']);
    // 更新接口
    Route::put('adminAction/update', [\App\Api\Admin\Controllers\AdminActionController::class, 'update']);
    // 删除接口
    Route::delete('adminAction/destroy', [\App\Api\Admin\Controllers\AdminActionController::class, 'destroy']);
    // 查询列表接口
    Route::post('adminLog/query', [\App\Api\Admin\Controllers\AdminLogController::class, 'query']);
    // 新增接口
    Route::post('adminLog/store', [\App\Api\Admin\Controllers\AdminLogController::class, 'store']);
    // 获取详情接口
    Route::get('adminLog/show', [\App\Api\Admin\Controllers\AdminLogController::class, 'show']);
    // 更新接口
    Route::put('adminLog/update', [\App\Api\Admin\Controllers\AdminLogController::class, 'update']);
    // 删除接口
    Route::delete('adminLog/destroy', [\App\Api\Admin\Controllers\AdminLogController::class, 'destroy']);
    // 查询列表接口
    Route::post('adminMessage/query', [\App\Api\Admin\Controllers\AdminMessageController::class, 'query']);
    // 新增接口
    Route::post('adminMessage/store', [\App\Api\Admin\Controllers\AdminMessageController::class, 'store']);
    // 获取详情接口
    Route::get('adminMessage/show', [\App\Api\Admin\Controllers\AdminMessageController::class, 'show']);
    // 更新接口
    Route::put('adminMessage/update', [\App\Api\Admin\Controllers\AdminMessageController::class, 'update']);
    // 删除接口
    Route::delete('adminMessage/destroy', [\App\Api\Admin\Controllers\AdminMessageController::class, 'destroy']);
    // 查询列表接口
    Route::post('adminUser/query', [\App\Api\Admin\Controllers\AdminUserController::class, 'query']);
    // 新增接口
    Route::post('adminUser/store', [\App\Api\Admin\Controllers\AdminUserController::class, 'store']);
    // 获取详情接口
    Route::get('adminUser/show', [\App\Api\Admin\Controllers\AdminUserController::class, 'show']);
    // 更新接口
    Route::put('adminUser/update', [\App\Api\Admin\Controllers\AdminUserController::class, 'update']);
    // 删除接口
    Route::delete('adminUser/destroy', [\App\Api\Admin\Controllers\AdminUserController::class, 'destroy']);
    // 查询列表接口
    Route::post('adsense/query', [\App\Api\Admin\Controllers\AdsenseController::class, 'query']);
    // 新增接口
    Route::post('adsense/store', [\App\Api\Admin\Controllers\AdsenseController::class, 'store']);
    // 获取详情接口
    Route::get('adsense/show', [\App\Api\Admin\Controllers\AdsenseController::class, 'show']);
    // 更新接口
    Route::put('adsense/update', [\App\Api\Admin\Controllers\AdsenseController::class, 'update']);
    // 删除接口
    Route::delete('adsense/destroy', [\App\Api\Admin\Controllers\AdsenseController::class, 'destroy']);
    // 查询列表接口
    Route::post('affiliateLog/query', [\App\Api\Admin\Controllers\AffiliateLogController::class, 'query']);
    // 新增接口
    Route::post('affiliateLog/store', [\App\Api\Admin\Controllers\AffiliateLogController::class, 'store']);
    // 获取详情接口
    Route::get('affiliateLog/show', [\App\Api\Admin\Controllers\AffiliateLogController::class, 'show']);
    // 更新接口
    Route::put('affiliateLog/update', [\App\Api\Admin\Controllers\AffiliateLogController::class, 'update']);
    // 删除接口
    Route::delete('affiliateLog/destroy', [\App\Api\Admin\Controllers\AffiliateLogController::class, 'destroy']);
    // 查询列表接口
    Route::post('agency/query', [\App\Api\Admin\Controllers\AgencyController::class, 'query']);
    // 新增接口
    Route::post('agency/store', [\App\Api\Admin\Controllers\AgencyController::class, 'store']);
    // 获取详情接口
    Route::get('agency/show', [\App\Api\Admin\Controllers\AgencyController::class, 'show']);
    // 更新接口
    Route::put('agency/update', [\App\Api\Admin\Controllers\AgencyController::class, 'update']);
    // 删除接口
    Route::delete('agency/destroy', [\App\Api\Admin\Controllers\AgencyController::class, 'destroy']);
    // 查询列表接口
    Route::post('areaRegion/query', [\App\Api\Admin\Controllers\AreaRegionController::class, 'query']);
    // 新增接口
    Route::post('areaRegion/store', [\App\Api\Admin\Controllers\AreaRegionController::class, 'store']);
    // 获取详情接口
    Route::get('areaRegion/show', [\App\Api\Admin\Controllers\AreaRegionController::class, 'show']);
    // 更新接口
    Route::put('areaRegion/update', [\App\Api\Admin\Controllers\AreaRegionController::class, 'update']);
    // 删除接口
    Route::delete('areaRegion/destroy', [\App\Api\Admin\Controllers\AreaRegionController::class, 'destroy']);
    // 查询列表接口
    Route::post('articleCat/query', [\App\Api\Admin\Controllers\ArticleCatController::class, 'query']);
    // 新增接口
    Route::post('articleCat/store', [\App\Api\Admin\Controllers\ArticleCatController::class, 'store']);
    // 获取详情接口
    Route::get('articleCat/show', [\App\Api\Admin\Controllers\ArticleCatController::class, 'show']);
    // 更新接口
    Route::put('articleCat/update', [\App\Api\Admin\Controllers\ArticleCatController::class, 'update']);
    // 删除接口
    Route::delete('articleCat/destroy', [\App\Api\Admin\Controllers\ArticleCatController::class, 'destroy']);
    // 查询列表接口
    Route::post('article/query', [\App\Api\Admin\Controllers\ArticleController::class, 'query']);
    // 新增接口
    Route::post('article/store', [\App\Api\Admin\Controllers\ArticleController::class, 'store']);
    // 获取详情接口
    Route::get('article/show', [\App\Api\Admin\Controllers\ArticleController::class, 'show']);
    // 更新接口
    Route::put('article/update', [\App\Api\Admin\Controllers\ArticleController::class, 'update']);
    // 删除接口
    Route::delete('article/destroy', [\App\Api\Admin\Controllers\ArticleController::class, 'destroy']);
    // 查询列表接口
    Route::post('attribute/query', [\App\Api\Admin\Controllers\AttributeController::class, 'query']);
    // 新增接口
    Route::post('attribute/store', [\App\Api\Admin\Controllers\AttributeController::class, 'store']);
    // 获取详情接口
    Route::get('attribute/show', [\App\Api\Admin\Controllers\AttributeController::class, 'show']);
    // 更新接口
    Route::put('attribute/update', [\App\Api\Admin\Controllers\AttributeController::class, 'update']);
    // 删除接口
    Route::delete('attribute/destroy', [\App\Api\Admin\Controllers\AttributeController::class, 'destroy']);
    // 查询列表接口
    Route::post('auctionLog/query', [\App\Api\Admin\Controllers\AuctionLogController::class, 'query']);
    // 新增接口
    Route::post('auctionLog/store', [\App\Api\Admin\Controllers\AuctionLogController::class, 'store']);
    // 获取详情接口
    Route::get('auctionLog/show', [\App\Api\Admin\Controllers\AuctionLogController::class, 'show']);
    // 更新接口
    Route::put('auctionLog/update', [\App\Api\Admin\Controllers\AuctionLogController::class, 'update']);
    // 删除接口
    Route::delete('auctionLog/destroy', [\App\Api\Admin\Controllers\AuctionLogController::class, 'destroy']);
    // 查询列表接口
    Route::post('autoManage/query', [\App\Api\Admin\Controllers\AutoManageController::class, 'query']);
    // 新增接口
    Route::post('autoManage/store', [\App\Api\Admin\Controllers\AutoManageController::class, 'store']);
    // 获取详情接口
    Route::get('autoManage/show', [\App\Api\Admin\Controllers\AutoManageController::class, 'show']);
    // 更新接口
    Route::put('autoManage/update', [\App\Api\Admin\Controllers\AutoManageController::class, 'update']);
    // 删除接口
    Route::delete('autoManage/destroy', [\App\Api\Admin\Controllers\AutoManageController::class, 'destroy']);
    // 查询列表接口
    Route::post('backGoods/query', [\App\Api\Admin\Controllers\BackGoodsController::class, 'query']);
    // 新增接口
    Route::post('backGoods/store', [\App\Api\Admin\Controllers\BackGoodsController::class, 'store']);
    // 获取详情接口
    Route::get('backGoods/show', [\App\Api\Admin\Controllers\BackGoodsController::class, 'show']);
    // 更新接口
    Route::put('backGoods/update', [\App\Api\Admin\Controllers\BackGoodsController::class, 'update']);
    // 删除接口
    Route::delete('backGoods/destroy', [\App\Api\Admin\Controllers\BackGoodsController::class, 'destroy']);
    // 查询列表接口
    Route::post('backOrder/query', [\App\Api\Admin\Controllers\BackOrderController::class, 'query']);
    // 新增接口
    Route::post('backOrder/store', [\App\Api\Admin\Controllers\BackOrderController::class, 'store']);
    // 获取详情接口
    Route::get('backOrder/show', [\App\Api\Admin\Controllers\BackOrderController::class, 'show']);
    // 更新接口
    Route::put('backOrder/update', [\App\Api\Admin\Controllers\BackOrderController::class, 'update']);
    // 删除接口
    Route::delete('backOrder/destroy', [\App\Api\Admin\Controllers\BackOrderController::class, 'destroy']);
    // 查询列表接口
    Route::post('bonusType/query', [\App\Api\Admin\Controllers\BonusTypeController::class, 'query']);
    // 新增接口
    Route::post('bonusType/store', [\App\Api\Admin\Controllers\BonusTypeController::class, 'store']);
    // 获取详情接口
    Route::get('bonusType/show', [\App\Api\Admin\Controllers\BonusTypeController::class, 'show']);
    // 更新接口
    Route::put('bonusType/update', [\App\Api\Admin\Controllers\BonusTypeController::class, 'update']);
    // 删除接口
    Route::delete('bonusType/destroy', [\App\Api\Admin\Controllers\BonusTypeController::class, 'destroy']);
    // 查询列表接口
    Route::post('bookingGoods/query', [\App\Api\Admin\Controllers\BookingGoodsController::class, 'query']);
    // 新增接口
    Route::post('bookingGoods/store', [\App\Api\Admin\Controllers\BookingGoodsController::class, 'store']);
    // 获取详情接口
    Route::get('bookingGoods/show', [\App\Api\Admin\Controllers\BookingGoodsController::class, 'show']);
    // 更新接口
    Route::put('bookingGoods/update', [\App\Api\Admin\Controllers\BookingGoodsController::class, 'update']);
    // 删除接口
    Route::delete('bookingGoods/destroy', [\App\Api\Admin\Controllers\BookingGoodsController::class, 'destroy']);
    // 查询列表接口
    Route::post('brand/query', [\App\Api\Admin\Controllers\BrandController::class, 'query']);
    // 新增接口
    Route::post('brand/store', [\App\Api\Admin\Controllers\BrandController::class, 'store']);
    // 获取详情接口
    Route::get('brand/show', [\App\Api\Admin\Controllers\BrandController::class, 'show']);
    // 更新接口
    Route::put('brand/update', [\App\Api\Admin\Controllers\BrandController::class, 'update']);
    // 删除接口
    Route::delete('brand/destroy', [\App\Api\Admin\Controllers\BrandController::class, 'destroy']);
    // 查询列表接口
    Route::post('card/query', [\App\Api\Admin\Controllers\CardController::class, 'query']);
    // 新增接口
    Route::post('card/store', [\App\Api\Admin\Controllers\CardController::class, 'store']);
    // 获取详情接口
    Route::get('card/show', [\App\Api\Admin\Controllers\CardController::class, 'show']);
    // 更新接口
    Route::put('card/update', [\App\Api\Admin\Controllers\CardController::class, 'update']);
    // 删除接口
    Route::delete('card/destroy', [\App\Api\Admin\Controllers\CardController::class, 'destroy']);
    // 查询列表接口
    Route::post('cart/query', [\App\Api\Admin\Controllers\CartController::class, 'query']);
    // 新增接口
    Route::post('cart/store', [\App\Api\Admin\Controllers\CartController::class, 'store']);
    // 获取详情接口
    Route::get('cart/show', [\App\Api\Admin\Controllers\CartController::class, 'show']);
    // 更新接口
    Route::put('cart/update', [\App\Api\Admin\Controllers\CartController::class, 'update']);
    // 删除接口
    Route::delete('cart/destroy', [\App\Api\Admin\Controllers\CartController::class, 'destroy']);
    // 查询列表接口
    Route::post('catRecommend/query', [\App\Api\Admin\Controllers\CatRecommendController::class, 'query']);
    // 新增接口
    Route::post('catRecommend/store', [\App\Api\Admin\Controllers\CatRecommendController::class, 'store']);
    // 获取详情接口
    Route::get('catRecommend/show', [\App\Api\Admin\Controllers\CatRecommendController::class, 'show']);
    // 更新接口
    Route::put('catRecommend/update', [\App\Api\Admin\Controllers\CatRecommendController::class, 'update']);
    // 删除接口
    Route::delete('catRecommend/destroy', [\App\Api\Admin\Controllers\CatRecommendController::class, 'destroy']);
    // 查询列表接口
    Route::post('category/query', [\App\Api\Admin\Controllers\CategoryController::class, 'query']);
    // 新增接口
    Route::post('category/store', [\App\Api\Admin\Controllers\CategoryController::class, 'store']);
    // 获取详情接口
    Route::get('category/show', [\App\Api\Admin\Controllers\CategoryController::class, 'show']);
    // 更新接口
    Route::put('category/update', [\App\Api\Admin\Controllers\CategoryController::class, 'update']);
    // 删除接口
    Route::delete('category/destroy', [\App\Api\Admin\Controllers\CategoryController::class, 'destroy']);
    // 查询列表接口
    Route::post('collectGoods/query', [\App\Api\Admin\Controllers\CollectGoodsController::class, 'query']);
    // 新增接口
    Route::post('collectGoods/store', [\App\Api\Admin\Controllers\CollectGoodsController::class, 'store']);
    // 获取详情接口
    Route::get('collectGoods/show', [\App\Api\Admin\Controllers\CollectGoodsController::class, 'show']);
    // 更新接口
    Route::put('collectGoods/update', [\App\Api\Admin\Controllers\CollectGoodsController::class, 'update']);
    // 删除接口
    Route::delete('collectGoods/destroy', [\App\Api\Admin\Controllers\CollectGoodsController::class, 'destroy']);
    // 查询列表接口
    Route::post('comment/query', [\App\Api\Admin\Controllers\CommentController::class, 'query']);
    // 新增接口
    Route::post('comment/store', [\App\Api\Admin\Controllers\CommentController::class, 'store']);
    // 获取详情接口
    Route::get('comment/show', [\App\Api\Admin\Controllers\CommentController::class, 'show']);
    // 更新接口
    Route::put('comment/update', [\App\Api\Admin\Controllers\CommentController::class, 'update']);
    // 删除接口
    Route::delete('comment/destroy', [\App\Api\Admin\Controllers\CommentController::class, 'destroy']);
    // 查询列表接口
    Route::post('crons/query', [\App\Api\Admin\Controllers\CronsController::class, 'query']);
    // 新增接口
    Route::post('crons/store', [\App\Api\Admin\Controllers\CronsController::class, 'store']);
    // 获取详情接口
    Route::get('crons/show', [\App\Api\Admin\Controllers\CronsController::class, 'show']);
    // 更新接口
    Route::put('crons/update', [\App\Api\Admin\Controllers\CronsController::class, 'update']);
    // 删除接口
    Route::delete('crons/destroy', [\App\Api\Admin\Controllers\CronsController::class, 'destroy']);
    // 查询列表接口
    Route::post('deliveryGoods/query', [\App\Api\Admin\Controllers\DeliveryGoodsController::class, 'query']);
    // 新增接口
    Route::post('deliveryGoods/store', [\App\Api\Admin\Controllers\DeliveryGoodsController::class, 'store']);
    // 获取详情接口
    Route::get('deliveryGoods/show', [\App\Api\Admin\Controllers\DeliveryGoodsController::class, 'show']);
    // 更新接口
    Route::put('deliveryGoods/update', [\App\Api\Admin\Controllers\DeliveryGoodsController::class, 'update']);
    // 删除接口
    Route::delete('deliveryGoods/destroy', [\App\Api\Admin\Controllers\DeliveryGoodsController::class, 'destroy']);
    // 查询列表接口
    Route::post('deliveryOrder/query', [\App\Api\Admin\Controllers\DeliveryOrderController::class, 'query']);
    // 新增接口
    Route::post('deliveryOrder/store', [\App\Api\Admin\Controllers\DeliveryOrderController::class, 'store']);
    // 获取详情接口
    Route::get('deliveryOrder/show', [\App\Api\Admin\Controllers\DeliveryOrderController::class, 'show']);
    // 更新接口
    Route::put('deliveryOrder/update', [\App\Api\Admin\Controllers\DeliveryOrderController::class, 'update']);
    // 删除接口
    Route::delete('deliveryOrder/destroy', [\App\Api\Admin\Controllers\DeliveryOrderController::class, 'destroy']);
    // 查询列表接口
    Route::post('emailList/query', [\App\Api\Admin\Controllers\EmailListController::class, 'query']);
    // 新增接口
    Route::post('emailList/store', [\App\Api\Admin\Controllers\EmailListController::class, 'store']);
    // 获取详情接口
    Route::get('emailList/show', [\App\Api\Admin\Controllers\EmailListController::class, 'show']);
    // 更新接口
    Route::put('emailList/update', [\App\Api\Admin\Controllers\EmailListController::class, 'update']);
    // 删除接口
    Route::delete('emailList/destroy', [\App\Api\Admin\Controllers\EmailListController::class, 'destroy']);
    // 查询列表接口
    Route::post('emailSendlist/query', [\App\Api\Admin\Controllers\EmailSendlistController::class, 'query']);
    // 新增接口
    Route::post('emailSendlist/store', [\App\Api\Admin\Controllers\EmailSendlistController::class, 'store']);
    // 获取详情接口
    Route::get('emailSendlist/show', [\App\Api\Admin\Controllers\EmailSendlistController::class, 'show']);
    // 更新接口
    Route::put('emailSendlist/update', [\App\Api\Admin\Controllers\EmailSendlistController::class, 'update']);
    // 删除接口
    Route::delete('emailSendlist/destroy', [\App\Api\Admin\Controllers\EmailSendlistController::class, 'destroy']);
    // 查询列表接口
    Route::post('errorLog/query', [\App\Api\Admin\Controllers\ErrorLogController::class, 'query']);
    // 新增接口
    Route::post('errorLog/store', [\App\Api\Admin\Controllers\ErrorLogController::class, 'store']);
    // 获取详情接口
    Route::get('errorLog/show', [\App\Api\Admin\Controllers\ErrorLogController::class, 'show']);
    // 更新接口
    Route::put('errorLog/update', [\App\Api\Admin\Controllers\ErrorLogController::class, 'update']);
    // 删除接口
    Route::delete('errorLog/destroy', [\App\Api\Admin\Controllers\ErrorLogController::class, 'destroy']);
    // 查询列表接口
    Route::post('exchangeGoods/query', [\App\Api\Admin\Controllers\ExchangeGoodsController::class, 'query']);
    // 新增接口
    Route::post('exchangeGoods/store', [\App\Api\Admin\Controllers\ExchangeGoodsController::class, 'store']);
    // 获取详情接口
    Route::get('exchangeGoods/show', [\App\Api\Admin\Controllers\ExchangeGoodsController::class, 'show']);
    // 更新接口
    Route::put('exchangeGoods/update', [\App\Api\Admin\Controllers\ExchangeGoodsController::class, 'update']);
    // 删除接口
    Route::delete('exchangeGoods/destroy', [\App\Api\Admin\Controllers\ExchangeGoodsController::class, 'destroy']);
    // 查询列表接口
    Route::post('favourableActivity/query', [\App\Api\Admin\Controllers\FavourableActivityController::class, 'query']);
    // 新增接口
    Route::post('favourableActivity/store', [\App\Api\Admin\Controllers\FavourableActivityController::class, 'store']);
    // 获取详情接口
    Route::get('favourableActivity/show', [\App\Api\Admin\Controllers\FavourableActivityController::class, 'show']);
    // 更新接口
    Route::put('favourableActivity/update', [\App\Api\Admin\Controllers\FavourableActivityController::class, 'update']);
    // 删除接口
    Route::delete('favourableActivity/destroy', [\App\Api\Admin\Controllers\FavourableActivityController::class, 'destroy']);
    // 查询列表接口
    Route::post('feedback/query', [\App\Api\Admin\Controllers\FeedbackController::class, 'query']);
    // 新增接口
    Route::post('feedback/store', [\App\Api\Admin\Controllers\FeedbackController::class, 'store']);
    // 获取详情接口
    Route::get('feedback/show', [\App\Api\Admin\Controllers\FeedbackController::class, 'show']);
    // 更新接口
    Route::put('feedback/update', [\App\Api\Admin\Controllers\FeedbackController::class, 'update']);
    // 删除接口
    Route::delete('feedback/destroy', [\App\Api\Admin\Controllers\FeedbackController::class, 'destroy']);
    // 查询列表接口
    Route::post('friendLink/query', [\App\Api\Admin\Controllers\FriendLinkController::class, 'query']);
    // 新增接口
    Route::post('friendLink/store', [\App\Api\Admin\Controllers\FriendLinkController::class, 'store']);
    // 获取详情接口
    Route::get('friendLink/show', [\App\Api\Admin\Controllers\FriendLinkController::class, 'show']);
    // 更新接口
    Route::put('friendLink/update', [\App\Api\Admin\Controllers\FriendLinkController::class, 'update']);
    // 删除接口
    Route::delete('friendLink/destroy', [\App\Api\Admin\Controllers\FriendLinkController::class, 'destroy']);
    // 查询列表接口
    Route::post('goodsActivity/query', [\App\Api\Admin\Controllers\GoodsActivityController::class, 'query']);
    // 新增接口
    Route::post('goodsActivity/store', [\App\Api\Admin\Controllers\GoodsActivityController::class, 'store']);
    // 获取详情接口
    Route::get('goodsActivity/show', [\App\Api\Admin\Controllers\GoodsActivityController::class, 'show']);
    // 更新接口
    Route::put('goodsActivity/update', [\App\Api\Admin\Controllers\GoodsActivityController::class, 'update']);
    // 删除接口
    Route::delete('goodsActivity/destroy', [\App\Api\Admin\Controllers\GoodsActivityController::class, 'destroy']);
    // 查询列表接口
    Route::post('goodsArticle/query', [\App\Api\Admin\Controllers\GoodsArticleController::class, 'query']);
    // 新增接口
    Route::post('goodsArticle/store', [\App\Api\Admin\Controllers\GoodsArticleController::class, 'store']);
    // 获取详情接口
    Route::get('goodsArticle/show', [\App\Api\Admin\Controllers\GoodsArticleController::class, 'show']);
    // 更新接口
    Route::put('goodsArticle/update', [\App\Api\Admin\Controllers\GoodsArticleController::class, 'update']);
    // 删除接口
    Route::delete('goodsArticle/destroy', [\App\Api\Admin\Controllers\GoodsArticleController::class, 'destroy']);
    // 查询列表接口
    Route::post('goodsAttr/query', [\App\Api\Admin\Controllers\GoodsAttrController::class, 'query']);
    // 新增接口
    Route::post('goodsAttr/store', [\App\Api\Admin\Controllers\GoodsAttrController::class, 'store']);
    // 获取详情接口
    Route::get('goodsAttr/show', [\App\Api\Admin\Controllers\GoodsAttrController::class, 'show']);
    // 更新接口
    Route::put('goodsAttr/update', [\App\Api\Admin\Controllers\GoodsAttrController::class, 'update']);
    // 删除接口
    Route::delete('goodsAttr/destroy', [\App\Api\Admin\Controllers\GoodsAttrController::class, 'destroy']);
    // 查询列表接口
    Route::post('goodsCat/query', [\App\Api\Admin\Controllers\GoodsCatController::class, 'query']);
    // 新增接口
    Route::post('goodsCat/store', [\App\Api\Admin\Controllers\GoodsCatController::class, 'store']);
    // 获取详情接口
    Route::get('goodsCat/show', [\App\Api\Admin\Controllers\GoodsCatController::class, 'show']);
    // 更新接口
    Route::put('goodsCat/update', [\App\Api\Admin\Controllers\GoodsCatController::class, 'update']);
    // 删除接口
    Route::delete('goodsCat/destroy', [\App\Api\Admin\Controllers\GoodsCatController::class, 'destroy']);
    // 查询列表接口
    Route::post('goods/query', [\App\Api\Admin\Controllers\GoodsController::class, 'query']);
    // 新增接口
    Route::post('goods/store', [\App\Api\Admin\Controllers\GoodsController::class, 'store']);
    // 获取详情接口
    Route::get('goods/show', [\App\Api\Admin\Controllers\GoodsController::class, 'show']);
    // 更新接口
    Route::put('goods/update', [\App\Api\Admin\Controllers\GoodsController::class, 'update']);
    // 删除接口
    Route::delete('goods/destroy', [\App\Api\Admin\Controllers\GoodsController::class, 'destroy']);
    // 查询列表接口
    Route::post('goodsGallery/query', [\App\Api\Admin\Controllers\GoodsGalleryController::class, 'query']);
    // 新增接口
    Route::post('goodsGallery/store', [\App\Api\Admin\Controllers\GoodsGalleryController::class, 'store']);
    // 获取详情接口
    Route::get('goodsGallery/show', [\App\Api\Admin\Controllers\GoodsGalleryController::class, 'show']);
    // 更新接口
    Route::put('goodsGallery/update', [\App\Api\Admin\Controllers\GoodsGalleryController::class, 'update']);
    // 删除接口
    Route::delete('goodsGallery/destroy', [\App\Api\Admin\Controllers\GoodsGalleryController::class, 'destroy']);
    // 查询列表接口
    Route::post('goodsType/query', [\App\Api\Admin\Controllers\GoodsTypeController::class, 'query']);
    // 新增接口
    Route::post('goodsType/store', [\App\Api\Admin\Controllers\GoodsTypeController::class, 'store']);
    // 获取详情接口
    Route::get('goodsType/show', [\App\Api\Admin\Controllers\GoodsTypeController::class, 'show']);
    // 更新接口
    Route::put('goodsType/update', [\App\Api\Admin\Controllers\GoodsTypeController::class, 'update']);
    // 删除接口
    Route::delete('goodsType/destroy', [\App\Api\Admin\Controllers\GoodsTypeController::class, 'destroy']);
    // 查询列表接口
    Route::post('groupGoods/query', [\App\Api\Admin\Controllers\GroupGoodsController::class, 'query']);
    // 新增接口
    Route::post('groupGoods/store', [\App\Api\Admin\Controllers\GroupGoodsController::class, 'store']);
    // 获取详情接口
    Route::get('groupGoods/show', [\App\Api\Admin\Controllers\GroupGoodsController::class, 'show']);
    // 更新接口
    Route::put('groupGoods/update', [\App\Api\Admin\Controllers\GroupGoodsController::class, 'update']);
    // 删除接口
    Route::delete('groupGoods/destroy', [\App\Api\Admin\Controllers\GroupGoodsController::class, 'destroy']);
    // 查询列表接口
    Route::post('keywords/query', [\App\Api\Admin\Controllers\KeywordsController::class, 'query']);
    // 新增接口
    Route::post('keywords/store', [\App\Api\Admin\Controllers\KeywordsController::class, 'store']);
    // 获取详情接口
    Route::get('keywords/show', [\App\Api\Admin\Controllers\KeywordsController::class, 'show']);
    // 更新接口
    Route::put('keywords/update', [\App\Api\Admin\Controllers\KeywordsController::class, 'update']);
    // 删除接口
    Route::delete('keywords/destroy', [\App\Api\Admin\Controllers\KeywordsController::class, 'destroy']);
    // 查询列表接口
    Route::post('linkGoods/query', [\App\Api\Admin\Controllers\LinkGoodsController::class, 'query']);
    // 新增接口
    Route::post('linkGoods/store', [\App\Api\Admin\Controllers\LinkGoodsController::class, 'store']);
    // 获取详情接口
    Route::get('linkGoods/show', [\App\Api\Admin\Controllers\LinkGoodsController::class, 'show']);
    // 更新接口
    Route::put('linkGoods/update', [\App\Api\Admin\Controllers\LinkGoodsController::class, 'update']);
    // 删除接口
    Route::delete('linkGoods/destroy', [\App\Api\Admin\Controllers\LinkGoodsController::class, 'destroy']);
    // 查询列表接口
    Route::post('mailTemplates/query', [\App\Api\Admin\Controllers\MailTemplatesController::class, 'query']);
    // 新增接口
    Route::post('mailTemplates/store', [\App\Api\Admin\Controllers\MailTemplatesController::class, 'store']);
    // 获取详情接口
    Route::get('mailTemplates/show', [\App\Api\Admin\Controllers\MailTemplatesController::class, 'show']);
    // 更新接口
    Route::put('mailTemplates/update', [\App\Api\Admin\Controllers\MailTemplatesController::class, 'update']);
    // 删除接口
    Route::delete('mailTemplates/destroy', [\App\Api\Admin\Controllers\MailTemplatesController::class, 'destroy']);
    // 查询列表接口
    Route::post('memberPrice/query', [\App\Api\Admin\Controllers\MemberPriceController::class, 'query']);
    // 新增接口
    Route::post('memberPrice/store', [\App\Api\Admin\Controllers\MemberPriceController::class, 'store']);
    // 获取详情接口
    Route::get('memberPrice/show', [\App\Api\Admin\Controllers\MemberPriceController::class, 'show']);
    // 更新接口
    Route::put('memberPrice/update', [\App\Api\Admin\Controllers\MemberPriceController::class, 'update']);
    // 删除接口
    Route::delete('memberPrice/destroy', [\App\Api\Admin\Controllers\MemberPriceController::class, 'destroy']);
    // 查询列表接口
    Route::post('nav/query', [\App\Api\Admin\Controllers\NavController::class, 'query']);
    // 新增接口
    Route::post('nav/store', [\App\Api\Admin\Controllers\NavController::class, 'store']);
    // 获取详情接口
    Route::get('nav/show', [\App\Api\Admin\Controllers\NavController::class, 'show']);
    // 更新接口
    Route::put('nav/update', [\App\Api\Admin\Controllers\NavController::class, 'update']);
    // 删除接口
    Route::delete('nav/destroy', [\App\Api\Admin\Controllers\NavController::class, 'destroy']);
    // 查询列表接口
    Route::post('orderAction/query', [\App\Api\Admin\Controllers\OrderActionController::class, 'query']);
    // 新增接口
    Route::post('orderAction/store', [\App\Api\Admin\Controllers\OrderActionController::class, 'store']);
    // 获取详情接口
    Route::get('orderAction/show', [\App\Api\Admin\Controllers\OrderActionController::class, 'show']);
    // 更新接口
    Route::put('orderAction/update', [\App\Api\Admin\Controllers\OrderActionController::class, 'update']);
    // 删除接口
    Route::delete('orderAction/destroy', [\App\Api\Admin\Controllers\OrderActionController::class, 'destroy']);
    // 查询列表接口
    Route::post('orderGoods/query', [\App\Api\Admin\Controllers\OrderGoodsController::class, 'query']);
    // 新增接口
    Route::post('orderGoods/store', [\App\Api\Admin\Controllers\OrderGoodsController::class, 'store']);
    // 获取详情接口
    Route::get('orderGoods/show', [\App\Api\Admin\Controllers\OrderGoodsController::class, 'show']);
    // 更新接口
    Route::put('orderGoods/update', [\App\Api\Admin\Controllers\OrderGoodsController::class, 'update']);
    // 删除接口
    Route::delete('orderGoods/destroy', [\App\Api\Admin\Controllers\OrderGoodsController::class, 'destroy']);
    // 查询列表接口
    Route::post('orderInfo/query', [\App\Api\Admin\Controllers\OrderInfoController::class, 'query']);
    // 新增接口
    Route::post('orderInfo/store', [\App\Api\Admin\Controllers\OrderInfoController::class, 'store']);
    // 获取详情接口
    Route::get('orderInfo/show', [\App\Api\Admin\Controllers\OrderInfoController::class, 'show']);
    // 更新接口
    Route::put('orderInfo/update', [\App\Api\Admin\Controllers\OrderInfoController::class, 'update']);
    // 删除接口
    Route::delete('orderInfo/destroy', [\App\Api\Admin\Controllers\OrderInfoController::class, 'destroy']);
    // 查询列表接口
    Route::post('pack/query', [\App\Api\Admin\Controllers\PackController::class, 'query']);
    // 新增接口
    Route::post('pack/store', [\App\Api\Admin\Controllers\PackController::class, 'store']);
    // 获取详情接口
    Route::get('pack/show', [\App\Api\Admin\Controllers\PackController::class, 'show']);
    // 更新接口
    Route::put('pack/update', [\App\Api\Admin\Controllers\PackController::class, 'update']);
    // 删除接口
    Route::delete('pack/destroy', [\App\Api\Admin\Controllers\PackController::class, 'destroy']);
    // 查询列表接口
    Route::post('packageGoods/query', [\App\Api\Admin\Controllers\PackageGoodsController::class, 'query']);
    // 新增接口
    Route::post('packageGoods/store', [\App\Api\Admin\Controllers\PackageGoodsController::class, 'store']);
    // 获取详情接口
    Route::get('packageGoods/show', [\App\Api\Admin\Controllers\PackageGoodsController::class, 'show']);
    // 更新接口
    Route::put('packageGoods/update', [\App\Api\Admin\Controllers\PackageGoodsController::class, 'update']);
    // 删除接口
    Route::delete('packageGoods/destroy', [\App\Api\Admin\Controllers\PackageGoodsController::class, 'destroy']);
    // 查询列表接口
    Route::post('payLog/query', [\App\Api\Admin\Controllers\PayLogController::class, 'query']);
    // 新增接口
    Route::post('payLog/store', [\App\Api\Admin\Controllers\PayLogController::class, 'store']);
    // 获取详情接口
    Route::get('payLog/show', [\App\Api\Admin\Controllers\PayLogController::class, 'show']);
    // 更新接口
    Route::put('payLog/update', [\App\Api\Admin\Controllers\PayLogController::class, 'update']);
    // 删除接口
    Route::delete('payLog/destroy', [\App\Api\Admin\Controllers\PayLogController::class, 'destroy']);
    // 查询列表接口
    Route::post('payment/query', [\App\Api\Admin\Controllers\PaymentController::class, 'query']);
    // 新增接口
    Route::post('payment/store', [\App\Api\Admin\Controllers\PaymentController::class, 'store']);
    // 获取详情接口
    Route::get('payment/show', [\App\Api\Admin\Controllers\PaymentController::class, 'show']);
    // 更新接口
    Route::put('payment/update', [\App\Api\Admin\Controllers\PaymentController::class, 'update']);
    // 删除接口
    Route::delete('payment/destroy', [\App\Api\Admin\Controllers\PaymentController::class, 'destroy']);
    // 查询列表接口
    Route::post('plugins/query', [\App\Api\Admin\Controllers\PluginsController::class, 'query']);
    // 新增接口
    Route::post('plugins/store', [\App\Api\Admin\Controllers\PluginsController::class, 'store']);
    // 获取详情接口
    Route::get('plugins/show', [\App\Api\Admin\Controllers\PluginsController::class, 'show']);
    // 更新接口
    Route::put('plugins/update', [\App\Api\Admin\Controllers\PluginsController::class, 'update']);
    // 删除接口
    Route::delete('plugins/destroy', [\App\Api\Admin\Controllers\PluginsController::class, 'destroy']);
    // 查询列表接口
    Route::post('product/query', [\App\Api\Admin\Controllers\ProductController::class, 'query']);
    // 新增接口
    Route::post('product/store', [\App\Api\Admin\Controllers\ProductController::class, 'store']);
    // 获取详情接口
    Route::get('product/show', [\App\Api\Admin\Controllers\ProductController::class, 'show']);
    // 更新接口
    Route::put('product/update', [\App\Api\Admin\Controllers\ProductController::class, 'update']);
    // 删除接口
    Route::delete('product/destroy', [\App\Api\Admin\Controllers\ProductController::class, 'destroy']);
    // 查询列表接口
    Route::post('regExtendInfo/query', [\App\Api\Admin\Controllers\RegExtendInfoController::class, 'query']);
    // 新增接口
    Route::post('regExtendInfo/store', [\App\Api\Admin\Controllers\RegExtendInfoController::class, 'store']);
    // 获取详情接口
    Route::get('regExtendInfo/show', [\App\Api\Admin\Controllers\RegExtendInfoController::class, 'show']);
    // 更新接口
    Route::put('regExtendInfo/update', [\App\Api\Admin\Controllers\RegExtendInfoController::class, 'update']);
    // 删除接口
    Route::delete('regExtendInfo/destroy', [\App\Api\Admin\Controllers\RegExtendInfoController::class, 'destroy']);
    // 查询列表接口
    Route::post('regFields/query', [\App\Api\Admin\Controllers\RegFieldsController::class, 'query']);
    // 新增接口
    Route::post('regFields/store', [\App\Api\Admin\Controllers\RegFieldsController::class, 'store']);
    // 获取详情接口
    Route::get('regFields/show', [\App\Api\Admin\Controllers\RegFieldsController::class, 'show']);
    // 更新接口
    Route::put('regFields/update', [\App\Api\Admin\Controllers\RegFieldsController::class, 'update']);
    // 删除接口
    Route::delete('regFields/destroy', [\App\Api\Admin\Controllers\RegFieldsController::class, 'destroy']);
    // 查询列表接口
    Route::post('region/query', [\App\Api\Admin\Controllers\RegionController::class, 'query']);
    // 新增接口
    Route::post('region/store', [\App\Api\Admin\Controllers\RegionController::class, 'store']);
    // 获取详情接口
    Route::get('region/show', [\App\Api\Admin\Controllers\RegionController::class, 'show']);
    // 更新接口
    Route::put('region/update', [\App\Api\Admin\Controllers\RegionController::class, 'update']);
    // 删除接口
    Route::delete('region/destroy', [\App\Api\Admin\Controllers\RegionController::class, 'destroy']);
    // 查询列表接口
    Route::post('role/query', [\App\Api\Admin\Controllers\RoleController::class, 'query']);
    // 新增接口
    Route::post('role/store', [\App\Api\Admin\Controllers\RoleController::class, 'store']);
    // 获取详情接口
    Route::get('role/show', [\App\Api\Admin\Controllers\RoleController::class, 'show']);
    // 更新接口
    Route::put('role/update', [\App\Api\Admin\Controllers\RoleController::class, 'update']);
    // 删除接口
    Route::delete('role/destroy', [\App\Api\Admin\Controllers\RoleController::class, 'destroy']);
    // 查询列表接口
    Route::post('searchEngine/query', [\App\Api\Admin\Controllers\SearchEngineController::class, 'query']);
    // 新增接口
    Route::post('searchEngine/store', [\App\Api\Admin\Controllers\SearchEngineController::class, 'store']);
    // 获取详情接口
    Route::get('searchEngine/show', [\App\Api\Admin\Controllers\SearchEngineController::class, 'show']);
    // 更新接口
    Route::put('searchEngine/update', [\App\Api\Admin\Controllers\SearchEngineController::class, 'update']);
    // 删除接口
    Route::delete('searchEngine/destroy', [\App\Api\Admin\Controllers\SearchEngineController::class, 'destroy']);
    // 查询列表接口
    Route::post('shippingArea/query', [\App\Api\Admin\Controllers\ShippingAreaController::class, 'query']);
    // 新增接口
    Route::post('shippingArea/store', [\App\Api\Admin\Controllers\ShippingAreaController::class, 'store']);
    // 获取详情接口
    Route::get('shippingArea/show', [\App\Api\Admin\Controllers\ShippingAreaController::class, 'show']);
    // 更新接口
    Route::put('shippingArea/update', [\App\Api\Admin\Controllers\ShippingAreaController::class, 'update']);
    // 删除接口
    Route::delete('shippingArea/destroy', [\App\Api\Admin\Controllers\ShippingAreaController::class, 'destroy']);
    // 查询列表接口
    Route::post('shipping/query', [\App\Api\Admin\Controllers\ShippingController::class, 'query']);
    // 新增接口
    Route::post('shipping/store', [\App\Api\Admin\Controllers\ShippingController::class, 'store']);
    // 获取详情接口
    Route::get('shipping/show', [\App\Api\Admin\Controllers\ShippingController::class, 'show']);
    // 更新接口
    Route::put('shipping/update', [\App\Api\Admin\Controllers\ShippingController::class, 'update']);
    // 删除接口
    Route::delete('shipping/destroy', [\App\Api\Admin\Controllers\ShippingController::class, 'destroy']);
    // 查询列表接口
    Route::post('shopConfig/query', [\App\Api\Admin\Controllers\ShopConfigController::class, 'query']);
    // 新增接口
    Route::post('shopConfig/store', [\App\Api\Admin\Controllers\ShopConfigController::class, 'store']);
    // 获取详情接口
    Route::get('shopConfig/show', [\App\Api\Admin\Controllers\ShopConfigController::class, 'show']);
    // 更新接口
    Route::put('shopConfig/update', [\App\Api\Admin\Controllers\ShopConfigController::class, 'update']);
    // 删除接口
    Route::delete('shopConfig/destroy', [\App\Api\Admin\Controllers\ShopConfigController::class, 'destroy']);
    // 查询列表接口
    Route::post('snatchLog/query', [\App\Api\Admin\Controllers\SnatchLogController::class, 'query']);
    // 新增接口
    Route::post('snatchLog/store', [\App\Api\Admin\Controllers\SnatchLogController::class, 'store']);
    // 获取详情接口
    Route::get('snatchLog/show', [\App\Api\Admin\Controllers\SnatchLogController::class, 'show']);
    // 更新接口
    Route::put('snatchLog/update', [\App\Api\Admin\Controllers\SnatchLogController::class, 'update']);
    // 删除接口
    Route::delete('snatchLog/destroy', [\App\Api\Admin\Controllers\SnatchLogController::class, 'destroy']);
    // 查询列表接口
    Route::post('stats/query', [\App\Api\Admin\Controllers\StatsController::class, 'query']);
    // 新增接口
    Route::post('stats/store', [\App\Api\Admin\Controllers\StatsController::class, 'store']);
    // 获取详情接口
    Route::get('stats/show', [\App\Api\Admin\Controllers\StatsController::class, 'show']);
    // 更新接口
    Route::put('stats/update', [\App\Api\Admin\Controllers\StatsController::class, 'update']);
    // 删除接口
    Route::delete('stats/destroy', [\App\Api\Admin\Controllers\StatsController::class, 'destroy']);
    // 查询列表接口
    Route::post('supplier/query', [\App\Api\Admin\Controllers\SupplierController::class, 'query']);
    // 新增接口
    Route::post('supplier/store', [\App\Api\Admin\Controllers\SupplierController::class, 'store']);
    // 获取详情接口
    Route::get('supplier/show', [\App\Api\Admin\Controllers\SupplierController::class, 'show']);
    // 更新接口
    Route::put('supplier/update', [\App\Api\Admin\Controllers\SupplierController::class, 'update']);
    // 删除接口
    Route::delete('supplier/destroy', [\App\Api\Admin\Controllers\SupplierController::class, 'destroy']);
    // 查询列表接口
    Route::post('tag/query', [\App\Api\Admin\Controllers\TagController::class, 'query']);
    // 新增接口
    Route::post('tag/store', [\App\Api\Admin\Controllers\TagController::class, 'store']);
    // 获取详情接口
    Route::get('tag/show', [\App\Api\Admin\Controllers\TagController::class, 'show']);
    // 更新接口
    Route::put('tag/update', [\App\Api\Admin\Controllers\TagController::class, 'update']);
    // 删除接口
    Route::delete('tag/destroy', [\App\Api\Admin\Controllers\TagController::class, 'destroy']);
    // 查询列表接口
    Route::post('template/query', [\App\Api\Admin\Controllers\TemplateController::class, 'query']);
    // 新增接口
    Route::post('template/store', [\App\Api\Admin\Controllers\TemplateController::class, 'store']);
    // 获取详情接口
    Route::get('template/show', [\App\Api\Admin\Controllers\TemplateController::class, 'show']);
    // 更新接口
    Route::put('template/update', [\App\Api\Admin\Controllers\TemplateController::class, 'update']);
    // 删除接口
    Route::delete('template/destroy', [\App\Api\Admin\Controllers\TemplateController::class, 'destroy']);
    // 查询列表接口
    Route::post('topic/query', [\App\Api\Admin\Controllers\TopicController::class, 'query']);
    // 新增接口
    Route::post('topic/store', [\App\Api\Admin\Controllers\TopicController::class, 'store']);
    // 获取详情接口
    Route::get('topic/show', [\App\Api\Admin\Controllers\TopicController::class, 'show']);
    // 更新接口
    Route::put('topic/update', [\App\Api\Admin\Controllers\TopicController::class, 'update']);
    // 删除接口
    Route::delete('topic/destroy', [\App\Api\Admin\Controllers\TopicController::class, 'destroy']);
    // 查询列表接口
    Route::post('userAccount/query', [\App\Api\Admin\Controllers\UserAccountController::class, 'query']);
    // 新增接口
    Route::post('userAccount/store', [\App\Api\Admin\Controllers\UserAccountController::class, 'store']);
    // 获取详情接口
    Route::get('userAccount/show', [\App\Api\Admin\Controllers\UserAccountController::class, 'show']);
    // 更新接口
    Route::put('userAccount/update', [\App\Api\Admin\Controllers\UserAccountController::class, 'update']);
    // 删除接口
    Route::delete('userAccount/destroy', [\App\Api\Admin\Controllers\UserAccountController::class, 'destroy']);
    // 查询列表接口
    Route::post('userAddress/query', [\App\Api\Admin\Controllers\UserAddressController::class, 'query']);
    // 新增接口
    Route::post('userAddress/store', [\App\Api\Admin\Controllers\UserAddressController::class, 'store']);
    // 获取详情接口
    Route::get('userAddress/show', [\App\Api\Admin\Controllers\UserAddressController::class, 'show']);
    // 更新接口
    Route::put('userAddress/update', [\App\Api\Admin\Controllers\UserAddressController::class, 'update']);
    // 删除接口
    Route::delete('userAddress/destroy', [\App\Api\Admin\Controllers\UserAddressController::class, 'destroy']);
    // 查询列表接口
    Route::post('userBonus/query', [\App\Api\Admin\Controllers\UserBonusController::class, 'query']);
    // 新增接口
    Route::post('userBonus/store', [\App\Api\Admin\Controllers\UserBonusController::class, 'store']);
    // 获取详情接口
    Route::get('userBonus/show', [\App\Api\Admin\Controllers\UserBonusController::class, 'show']);
    // 更新接口
    Route::put('userBonus/update', [\App\Api\Admin\Controllers\UserBonusController::class, 'update']);
    // 删除接口
    Route::delete('userBonus/destroy', [\App\Api\Admin\Controllers\UserBonusController::class, 'destroy']);
    // 查询列表接口
    Route::post('user/query', [\App\Api\Admin\Controllers\UserController::class, 'query']);
    // 新增接口
    Route::post('user/store', [\App\Api\Admin\Controllers\UserController::class, 'store']);
    // 获取详情接口
    Route::get('user/show', [\App\Api\Admin\Controllers\UserController::class, 'show']);
    // 更新接口
    Route::put('user/update', [\App\Api\Admin\Controllers\UserController::class, 'update']);
    // 删除接口
    Route::delete('user/destroy', [\App\Api\Admin\Controllers\UserController::class, 'destroy']);
    // 查询列表接口
    Route::post('userFeed/query', [\App\Api\Admin\Controllers\UserFeedController::class, 'query']);
    // 新增接口
    Route::post('userFeed/store', [\App\Api\Admin\Controllers\UserFeedController::class, 'store']);
    // 获取详情接口
    Route::get('userFeed/show', [\App\Api\Admin\Controllers\UserFeedController::class, 'show']);
    // 更新接口
    Route::put('userFeed/update', [\App\Api\Admin\Controllers\UserFeedController::class, 'update']);
    // 删除接口
    Route::delete('userFeed/destroy', [\App\Api\Admin\Controllers\UserFeedController::class, 'destroy']);
    // 查询列表接口
    Route::post('userRank/query', [\App\Api\Admin\Controllers\UserRankController::class, 'query']);
    // 新增接口
    Route::post('userRank/store', [\App\Api\Admin\Controllers\UserRankController::class, 'store']);
    // 获取详情接口
    Route::get('userRank/show', [\App\Api\Admin\Controllers\UserRankController::class, 'show']);
    // 更新接口
    Route::put('userRank/update', [\App\Api\Admin\Controllers\UserRankController::class, 'update']);
    // 删除接口
    Route::delete('userRank/destroy', [\App\Api\Admin\Controllers\UserRankController::class, 'destroy']);
    // 查询列表接口
    Route::post('virtualCard/query', [\App\Api\Admin\Controllers\VirtualCardController::class, 'query']);
    // 新增接口
    Route::post('virtualCard/store', [\App\Api\Admin\Controllers\VirtualCardController::class, 'store']);
    // 获取详情接口
    Route::get('virtualCard/show', [\App\Api\Admin\Controllers\VirtualCardController::class, 'show']);
    // 更新接口
    Route::put('virtualCard/update', [\App\Api\Admin\Controllers\VirtualCardController::class, 'update']);
    // 删除接口
    Route::delete('virtualCard/destroy', [\App\Api\Admin\Controllers\VirtualCardController::class, 'destroy']);
    // 查询列表接口
    Route::post('volumePrice/query', [\App\Api\Admin\Controllers\VolumePriceController::class, 'query']);
    // 新增接口
    Route::post('volumePrice/store', [\App\Api\Admin\Controllers\VolumePriceController::class, 'store']);
    // 获取详情接口
    Route::get('volumePrice/show', [\App\Api\Admin\Controllers\VolumePriceController::class, 'show']);
    // 更新接口
    Route::put('volumePrice/update', [\App\Api\Admin\Controllers\VolumePriceController::class, 'update']);
    // 删除接口
    Route::delete('volumePrice/destroy', [\App\Api\Admin\Controllers\VolumePriceController::class, 'destroy']);
    // 查询列表接口
    Route::post('vote/query', [\App\Api\Admin\Controllers\VoteController::class, 'query']);
    // 新增接口
    Route::post('vote/store', [\App\Api\Admin\Controllers\VoteController::class, 'store']);
    // 获取详情接口
    Route::get('vote/show', [\App\Api\Admin\Controllers\VoteController::class, 'show']);
    // 更新接口
    Route::put('vote/update', [\App\Api\Admin\Controllers\VoteController::class, 'update']);
    // 删除接口
    Route::delete('vote/destroy', [\App\Api\Admin\Controllers\VoteController::class, 'destroy']);
    // 查询列表接口
    Route::post('voteLog/query', [\App\Api\Admin\Controllers\VoteLogController::class, 'query']);
    // 新增接口
    Route::post('voteLog/store', [\App\Api\Admin\Controllers\VoteLogController::class, 'store']);
    // 获取详情接口
    Route::get('voteLog/show', [\App\Api\Admin\Controllers\VoteLogController::class, 'show']);
    // 更新接口
    Route::put('voteLog/update', [\App\Api\Admin\Controllers\VoteLogController::class, 'update']);
    // 删除接口
    Route::delete('voteLog/destroy', [\App\Api\Admin\Controllers\VoteLogController::class, 'destroy']);
    // 查询列表接口
    Route::post('voteOption/query', [\App\Api\Admin\Controllers\VoteOptionController::class, 'query']);
    // 新增接口
    Route::post('voteOption/store', [\App\Api\Admin\Controllers\VoteOptionController::class, 'store']);
    // 获取详情接口
    Route::get('voteOption/show', [\App\Api\Admin\Controllers\VoteOptionController::class, 'show']);
    // 更新接口
    Route::put('voteOption/update', [\App\Api\Admin\Controllers\VoteOptionController::class, 'update']);
    // 删除接口
    Route::delete('voteOption/destroy', [\App\Api\Admin\Controllers\VoteOptionController::class, 'destroy']);
    // 查询列表接口
    Route::post('wholesale/query', [\App\Api\Admin\Controllers\WholesaleController::class, 'query']);
    // 新增接口
    Route::post('wholesale/store', [\App\Api\Admin\Controllers\WholesaleController::class, 'store']);
    // 获取详情接口
    Route::get('wholesale/show', [\App\Api\Admin\Controllers\WholesaleController::class, 'show']);
    // 更新接口
    Route::put('wholesale/update', [\App\Api\Admin\Controllers\WholesaleController::class, 'update']);
    // 删除接口
    Route::delete('wholesale/destroy', [\App\Api\Admin\Controllers\WholesaleController::class, 'destroy']);
});
// end
