<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group('auth', function () {
    Route::post('login', 'LoginController@index');
})->namespace('app\api\auth\controller');
