<?php

declare(strict_types=1);

namespace app\modules\admin\request\orderBackOrder;

use OpenApi\Attributes as OA;
use think\Validate;

#[OA\Schema(
    schema: 'OrderBackOrderCreateRequest',
    required: [
        'id',
        'delivery_sn',
        'order_sn',
        'order_id',
        'invoice_no',
        'add_time',
        'shipping_id',
        'shipping_name',
        'user_id',
        'action_user',
        'consignee',
        'address',
        'country',
        'province',
        'city',
        'district',
        'sign_building',
        'email',
        'zipcode',
        'tel',
        'mobile',
        'best_time',
        'postscript',
        'how_oos',
        'insure_fee',
        'shipping_fee',
        'supplier_id',
        'status',
        'return_time',
        'agency_id',
        'created_time',
        'updated_time',
        'deleted_time',
    ],
    properties: [
        new OA\Property(property: 'id', description: '退货单ID', type: 'integer'),
        new OA\Property(property: 'delivery_sn', description: '物流单号', type: 'string'),
        new OA\Property(property: 'order_sn', description: '订单号', type: 'string'),
        new OA\Property(property: 'order_id', description: '订单ID', type: 'integer'),
        new OA\Property(property: 'invoice_no', description: '发票号', type: 'string'),
        new OA\Property(property: 'add_time', description: '添加时间', type: 'integer'),
        new OA\Property(property: 'shipping_id', description: '配送方式ID', type: 'integer'),
        new OA\Property(property: 'shipping_name', description: '配送方式名称', type: 'string'),
        new OA\Property(property: 'user_id', description: '用户ID', type: 'integer'),
        new OA\Property(property: 'action_user', description: '操作人', type: 'string'),
        new OA\Property(property: 'consignee', description: '收货人', type: 'string'),
        new OA\Property(property: 'address', description: '收货地址', type: 'string'),
        new OA\Property(property: 'country', description: '国家ID', type: 'integer'),
        new OA\Property(property: 'province', description: '省份ID', type: 'integer'),
        new OA\Property(property: 'city', description: '城市ID', type: 'integer'),
        new OA\Property(property: 'district', description: '区县ID', type: 'integer'),
        new OA\Property(property: 'sign_building', description: '标志性建筑', type: 'string'),
        new OA\Property(property: 'email', description: '邮箱', type: 'string'),
        new OA\Property(property: 'zipcode', description: '邮编', type: 'string'),
        new OA\Property(property: 'tel', description: '电话', type: 'string'),
        new OA\Property(property: 'mobile', description: '手机', type: 'string'),
        new OA\Property(property: 'best_time', description: '最佳送货时间', type: 'string'),
        new OA\Property(property: 'postscript', description: '订单附言', type: 'string'),
        new OA\Property(property: 'how_oos', description: '缺货处理方式', type: 'string'),
        new OA\Property(property: 'insure_fee', description: '保价费用', type: 'float'),
        new OA\Property(property: 'shipping_fee', description: '配送费用', type: 'float'),
        new OA\Property(property: 'supplier_id', description: '供应商ID', type: 'integer'),
        new OA\Property(property: 'status', description: '退货状态', type: 'integer'),
        new OA\Property(property: 'return_time', description: '退货时间', type: 'integer'),
        new OA\Property(property: 'agency_id', description: '办事处ID', type: 'integer'),
        new OA\Property(property: 'created_time', description: '创建时间', type: 'string'),
        new OA\Property(property: 'updated_time', description: '更新时间', type: 'string'),
        new OA\Property(property: 'deleted_time', description: '删除时间', type: 'string'),
    ]
)]
class OrderBackOrderCreateRequest extends Validate
{
    protected $rule = [
        'id' => 'require',
        'delivery_sn' => 'require',
        'order_sn' => 'require',
        'order_id' => 'require',
        'invoice_no' => 'require',
        'add_time' => 'require',
        'shipping_id' => 'require',
        'shipping_name' => 'require',
        'user_id' => 'require',
        'action_user' => 'require',
        'consignee' => 'require',
        'address' => 'require',
        'country' => 'require',
        'province' => 'require',
        'city' => 'require',
        'district' => 'require',
        'sign_building' => 'require',
        'email' => 'require',
        'zipcode' => 'require',
        'tel' => 'require',
        'mobile' => 'require',
        'best_time' => 'require',
        'postscript' => 'require',
        'how_oos' => 'require',
        'insure_fee' => 'require',
        'shipping_fee' => 'require',
        'supplier_id' => 'require',
        'status' => 'require',
        'return_time' => 'require',
        'agency_id' => 'require',
        'created_time' => 'require',
        'updated_time' => 'require',
        'deleted_time' => 'require',
    ];

    protected $message = [
        'id.require' => '请设置退货单ID',
        'delivery_sn.require' => '请设置物流单号',
        'order_sn.require' => '请设置订单号',
        'order_id.require' => '请设置订单ID',
        'invoice_no.require' => '请设置发票号',
        'add_time.require' => '请设置添加时间',
        'shipping_id.require' => '请设置配送方式ID',
        'shipping_name.require' => '请设置配送方式名称',
        'user_id.require' => '请设置用户ID',
        'action_user.require' => '请设置操作人',
        'consignee.require' => '请设置收货人',
        'address.require' => '请设置收货地址',
        'country.require' => '请设置国家ID',
        'province.require' => '请设置省份ID',
        'city.require' => '请设置城市ID',
        'district.require' => '请设置区县ID',
        'sign_building.require' => '请设置标志性建筑',
        'email.require' => '请设置邮箱',
        'zipcode.require' => '请设置邮编',
        'tel.require' => '请设置电话',
        'mobile.require' => '请设置手机',
        'best_time.require' => '请设置最佳送货时间',
        'postscript.require' => '请设置订单附言',
        'how_oos.require' => '请设置缺货处理方式',
        'insure_fee.require' => '请设置保价费用',
        'shipping_fee.require' => '请设置配送费用',
        'supplier_id.require' => '请设置供应商ID',
        'status.require' => '请设置退货状态',
        'return_time.require' => '请设置退货时间',
        'agency_id.require' => '请设置办事处ID',
        'created_time.require' => '请设置创建时间',
        'updated_time.require' => '请设置更新时间',
        'deleted_time.require' => '请设置删除时间',
    ];
}
