<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group('common', function () {
    Route::post('captcha/image', 'CaptchaController@image');
    Route::post('sms/send', 'SmsController@send');
})->namespace('app\api\common\controller');
