<?php

declare(strict_types=1);

namespace app\modules\admin\request\orderInfo;

use OpenApi\Attributes as OA;
use think\Validate;

#[OA\Schema(
    schema: 'OrderInfoCreateRequest',
    required: [
        'id',
        'order_sn',
        'user_id',
        'order_status',
        'shipping_status',
        'pay_status',
        'consignee',
        'country',
        'province',
        'city',
        'district',
        'address',
        'zipcode',
        'tel',
        'mobile',
        'email',
        'best_time',
        'sign_building',
        'postscript',
        'shipping_id',
        'shipping_name',
        'pay_id',
        'pay_name',
        'how_oos',
        'how_surplus',
        'pack_name',
        'card_name',
        'card_message',
        'inv_payee',
        'inv_content',
        'goods_amount',
        'shipping_fee',
        'insure_fee',
        'pay_fee',
        'pack_fee',
        'card_fee',
        'money_paid',
        'surplus',
        'integral',
        'integral_money',
        'bonus',
        'order_amount',
        'from_ad',
        'referer',
        'add_time',
        'confirm_time',
        'pay_time',
        'shipping_time',
        'pack_id',
        'card_id',
        'bonus_id',
        'invoice_no',
        'extension_code',
        'extension_id',
        'to_buyer',
        'pay_note',
        'agency_id',
        'inv_type',
        'tax',
        'is_separate',
        'parent_id',
        'discount',
        'created_time',
        'updated_time',
        'deleted_time',
    ],
    properties: [
        new OA\Property(property: 'id', description: '订单ID', type: 'integer'),
        new OA\Property(property: 'order_sn', description: '订单编号', type: 'string'),
        new OA\Property(property: 'user_id', description: '用户ID', type: 'integer'),
        new OA\Property(property: 'order_status', description: '订单状态', type: 'integer'),
        new OA\Property(property: 'shipping_status', description: '配送状态', type: 'integer'),
        new OA\Property(property: 'pay_status', description: '支付状态', type: 'integer'),
        new OA\Property(property: 'consignee', description: '收货人', type: 'string'),
        new OA\Property(property: 'country', description: '国家ID', type: 'integer'),
        new OA\Property(property: 'province', description: '省份ID', type: 'integer'),
        new OA\Property(property: 'city', description: '城市ID', type: 'integer'),
        new OA\Property(property: 'district', description: '区县ID', type: 'integer'),
        new OA\Property(property: 'address', description: '详细地址', type: 'string'),
        new OA\Property(property: 'zipcode', description: '邮编', type: 'string'),
        new OA\Property(property: 'tel', description: '电话', type: 'string'),
        new OA\Property(property: 'mobile', description: '手机', type: 'string'),
        new OA\Property(property: 'email', description: '邮箱', type: 'string'),
        new OA\Property(property: 'best_time', description: '最佳送货时间', type: 'string'),
        new OA\Property(property: 'sign_building', description: '标志性建筑', type: 'string'),
        new OA\Property(property: 'postscript', description: '订单附言', type: 'string'),
        new OA\Property(property: 'shipping_id', description: '配送方式ID', type: 'integer'),
        new OA\Property(property: 'shipping_name', description: '配送方式名称', type: 'string'),
        new OA\Property(property: 'pay_id', description: '支付方式ID', type: 'integer'),
        new OA\Property(property: 'pay_name', description: '支付方式名称', type: 'string'),
        new OA\Property(property: 'how_oos', description: '缺货处理方式', type: 'string'),
        new OA\Property(property: 'how_surplus', description: '余额处理方式', type: 'string'),
        new OA\Property(property: 'pack_name', description: '包装名称', type: 'string'),
        new OA\Property(property: 'card_name', description: '贺卡名称', type: 'string'),
        new OA\Property(property: 'card_message', description: '贺卡留言', type: 'string'),
        new OA\Property(property: 'inv_payee', description: '发票抬头', type: 'string'),
        new OA\Property(property: 'inv_content', description: '发票内容', type: 'string'),
        new OA\Property(property: 'goods_amount', description: '商品总金额', type: 'float'),
        new OA\Property(property: 'shipping_fee', description: '配送费用', type: 'float'),
        new OA\Property(property: 'insure_fee', description: '保价费用', type: 'float'),
        new OA\Property(property: 'pay_fee', description: '支付手续费', type: 'float'),
        new OA\Property(property: 'pack_fee', description: '包装费用', type: 'float'),
        new OA\Property(property: 'card_fee', description: '贺卡费用', type: 'float'),
        new OA\Property(property: 'money_paid', description: '已付款金额', type: 'float'),
        new OA\Property(property: 'surplus', description: '余额支付金额', type: 'float'),
        new OA\Property(property: 'integral', description: '使用积分', type: 'integer'),
        new OA\Property(property: 'integral_money', description: '积分抵扣金额', type: 'float'),
        new OA\Property(property: 'bonus', description: '红包金额', type: 'float'),
        new OA\Property(property: 'order_amount', description: '订单总金额', type: 'float'),
        new OA\Property(property: 'from_ad', description: '来源广告ID', type: 'integer'),
        new OA\Property(property: 'referer', description: '来源页面', type: 'string'),
        new OA\Property(property: 'add_time', description: '添加时间', type: 'integer'),
        new OA\Property(property: 'confirm_time', description: '确认时间', type: 'integer'),
        new OA\Property(property: 'pay_time', description: '支付时间', type: 'integer'),
        new OA\Property(property: 'shipping_time', description: '发货时间', type: 'integer'),
        new OA\Property(property: 'pack_id', description: '包装ID', type: 'integer'),
        new OA\Property(property: 'card_id', description: '贺卡ID', type: 'integer'),
        new OA\Property(property: 'bonus_id', description: '红包ID', type: 'integer'),
        new OA\Property(property: 'invoice_no', description: '发货单号', type: 'string'),
        new OA\Property(property: 'extension_code', description: '扩展代码', type: 'string'),
        new OA\Property(property: 'extension_id', description: '扩展ID', type: 'integer'),
        new OA\Property(property: 'to_buyer', description: '给买家留言', type: 'string'),
        new OA\Property(property: 'pay_note', description: '支付备注', type: 'string'),
        new OA\Property(property: 'agency_id', description: '办事处ID', type: 'integer'),
        new OA\Property(property: 'inv_type', description: '发票类型', type: 'string'),
        new OA\Property(property: 'tax', description: '税费', type: 'float'),
        new OA\Property(property: 'is_separate', description: '是否分单', type: 'integer'),
        new OA\Property(property: 'parent_id', description: '父订单ID', type: 'integer'),
        new OA\Property(property: 'discount', description: '折扣金额', type: 'float'),
        new OA\Property(property: 'created_time', description: '创建时间', type: 'string'),
        new OA\Property(property: 'updated_time', description: '更新时间', type: 'string'),
        new OA\Property(property: 'deleted_time', description: '删除时间', type: 'string'),
    ]
)]
class OrderInfoCreateRequest extends Validate
{
    protected $rule = [
        'id' => 'require',
        'order_sn' => 'require',
        'user_id' => 'require',
        'order_status' => 'require',
        'shipping_status' => 'require',
        'pay_status' => 'require',
        'consignee' => 'require',
        'country' => 'require',
        'province' => 'require',
        'city' => 'require',
        'district' => 'require',
        'address' => 'require',
        'zipcode' => 'require',
        'tel' => 'require',
        'mobile' => 'require',
        'email' => 'require',
        'best_time' => 'require',
        'sign_building' => 'require',
        'postscript' => 'require',
        'shipping_id' => 'require',
        'shipping_name' => 'require',
        'pay_id' => 'require',
        'pay_name' => 'require',
        'how_oos' => 'require',
        'how_surplus' => 'require',
        'pack_name' => 'require',
        'card_name' => 'require',
        'card_message' => 'require',
        'inv_payee' => 'require',
        'inv_content' => 'require',
        'goods_amount' => 'require',
        'shipping_fee' => 'require',
        'insure_fee' => 'require',
        'pay_fee' => 'require',
        'pack_fee' => 'require',
        'card_fee' => 'require',
        'money_paid' => 'require',
        'surplus' => 'require',
        'integral' => 'require',
        'integral_money' => 'require',
        'bonus' => 'require',
        'order_amount' => 'require',
        'from_ad' => 'require',
        'referer' => 'require',
        'add_time' => 'require',
        'confirm_time' => 'require',
        'pay_time' => 'require',
        'shipping_time' => 'require',
        'pack_id' => 'require',
        'card_id' => 'require',
        'bonus_id' => 'require',
        'invoice_no' => 'require',
        'extension_code' => 'require',
        'extension_id' => 'require',
        'to_buyer' => 'require',
        'pay_note' => 'require',
        'agency_id' => 'require',
        'inv_type' => 'require',
        'tax' => 'require',
        'is_separate' => 'require',
        'parent_id' => 'require',
        'discount' => 'require',
        'created_time' => 'require',
        'updated_time' => 'require',
        'deleted_time' => 'require',
    ];

    protected $message = [
        'id.require' => '请设置订单ID',
        'order_sn.require' => '请设置订单编号',
        'user_id.require' => '请设置用户ID',
        'order_status.require' => '请设置订单状态',
        'shipping_status.require' => '请设置配送状态',
        'pay_status.require' => '请设置支付状态',
        'consignee.require' => '请设置收货人',
        'country.require' => '请设置国家ID',
        'province.require' => '请设置省份ID',
        'city.require' => '请设置城市ID',
        'district.require' => '请设置区县ID',
        'address.require' => '请设置详细地址',
        'zipcode.require' => '请设置邮编',
        'tel.require' => '请设置电话',
        'mobile.require' => '请设置手机',
        'email.require' => '请设置邮箱',
        'best_time.require' => '请设置最佳送货时间',
        'sign_building.require' => '请设置标志性建筑',
        'postscript.require' => '请设置订单附言',
        'shipping_id.require' => '请设置配送方式ID',
        'shipping_name.require' => '请设置配送方式名称',
        'pay_id.require' => '请设置支付方式ID',
        'pay_name.require' => '请设置支付方式名称',
        'how_oos.require' => '请设置缺货处理方式',
        'how_surplus.require' => '请设置余额处理方式',
        'pack_name.require' => '请设置包装名称',
        'card_name.require' => '请设置贺卡名称',
        'card_message.require' => '请设置贺卡留言',
        'inv_payee.require' => '请设置发票抬头',
        'inv_content.require' => '请设置发票内容',
        'goods_amount.require' => '请设置商品总金额',
        'shipping_fee.require' => '请设置配送费用',
        'insure_fee.require' => '请设置保价费用',
        'pay_fee.require' => '请设置支付手续费',
        'pack_fee.require' => '请设置包装费用',
        'card_fee.require' => '请设置贺卡费用',
        'money_paid.require' => '请设置已付款金额',
        'surplus.require' => '请设置余额支付金额',
        'integral.require' => '请设置使用积分',
        'integral_money.require' => '请设置积分抵扣金额',
        'bonus.require' => '请设置红包金额',
        'order_amount.require' => '请设置订单总金额',
        'from_ad.require' => '请设置来源广告ID',
        'referer.require' => '请设置来源页面',
        'add_time.require' => '请设置添加时间',
        'confirm_time.require' => '请设置确认时间',
        'pay_time.require' => '请设置支付时间',
        'shipping_time.require' => '请设置发货时间',
        'pack_id.require' => '请设置包装ID',
        'card_id.require' => '请设置贺卡ID',
        'bonus_id.require' => '请设置红包ID',
        'invoice_no.require' => '请设置发货单号',
        'extension_code.require' => '请设置扩展代码',
        'extension_id.require' => '请设置扩展ID',
        'to_buyer.require' => '请设置给买家留言',
        'pay_note.require' => '请设置支付备注',
        'agency_id.require' => '请设置办事处ID',
        'inv_type.require' => '请设置发票类型',
        'tax.require' => '请设置税费',
        'is_separate.require' => '请设置是否分单',
        'parent_id.require' => '请设置父订单ID',
        'discount.require' => '请设置折扣金额',
        'created_time.require' => '请设置创建时间',
        'updated_time.require' => '请设置更新时间',
        'deleted_time.require' => '请设置删除时间',
    ];
}
