<?php

// ==========================================================================
// Code generated by gen:module:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// admin route start
Route::prefix('admin')->middleware('web')->name('admin.')->group(function () {
    // 登录接口
    Route::get('login', [\App\Modules\Admin\Controllers\LoginController::class, 'showForm'])->name('login');
});
// end
