<?php

declare(strict_types=1);

use App\Modules\Admin\Controllers;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->middleware('web')->name('admin.')->group(function () {
    Route::get('login', [Controllers\AuthController::class, 'showLoginForm'])->name('login');
    Route::post('login', [Controllers\AuthController::class, 'login']);
    Route::middleware('auth:admin')->group(function () {
        Route::any('/', Controllers\IndexController::class);
        Route::any('account_log.php', Controllers\AccountLogController::class);
        Route::any('ad_position.php', Controllers\AdPositionController::class);
        Route::any('admin_logs.php', Controllers\AdminLogsController::class);
        Route::any('ads.php', Controllers\AdsController::class);
        Route::any('adsense.php', Controllers\AdsenseController::class);
        Route::any('affiliate_ck.php', Controllers\AffiliateCkController::class);
        Route::any('affiliate.php', Controllers\AffiliateController::class);
        Route::any('agency.php', Controllers\AgencyController::class);
        Route::any('area_manage.php', Controllers\AreaManageController::class);
        Route::any('article_auto.php', Controllers\ArticleAutoController::class);
        Route::any('article.php', Controllers\ArticleController::class);
        Route::any('articlecat.php', Controllers\ArticlecatController::class);
        Route::any('attention_list.php', Controllers\AttentionListController::class);
        Route::any('attribute.php', Controllers\AttributeController::class);
        Route::any('auction.php', Controllers\AuctionController::class);
        Route::any('bonus.php', Controllers\BonusController::class);
        Route::any('brand.php', Controllers\BrandController::class);
        Route::any('captcha_manage.php', Controllers\CaptchaManageController::class);
        Route::any('card.php', Controllers\CardController::class);
        Route::any('category.php', Controllers\CategoryController::class);
        Route::any('check_file_priv.php', Controllers\CheckFilePrivController::class);
        Route::any('cloud.php', Controllers\CloudController::class);
        Route::any('comment_manage.php', Controllers\CommentManageController::class);
        Route::any('convert.php', Controllers\ConvertController::class);
        Route::any('cron.php', Controllers\CronController::class);
        Route::any('database.php', Controllers\DatabaseController::class);
        Route::any('edit_languages.php', Controllers\EditLanguagesController::class);
        Route::any('email_list.php', Controllers\EmailListController::class);
        Route::any('exchange_goods.php', Controllers\ExchangeGoodsController::class);
        Route::any('favourable.php', Controllers\FavourableController::class);
        Route::any('filecheck.php', Controllers\FileCheckController::class);
        Route::any('flashplay.php', Controllers\FlashplayController::class);
        Route::any('flow_stats.php', Controllers\FlowStatsController::class);
        Route::any('friend_link.php', Controllers\FriendLinkController::class);
        Route::any('gen_goods_script.php', Controllers\GenGoodsScriptController::class);
        Route::any('get_password.php', Controllers\GetPasswordController::class);
        Route::any('goods_auto.php', Controllers\GoodsAutoController::class);
        Route::any('goods_batch.php', Controllers\GoodsBatchController::class);
        Route::any('goods_booking.php', Controllers\GoodsBookingController::class);
        Route::any('goods_export.php', Controllers\GoodsExportController::class);
        Route::any('goods_type.php', Controllers\GoodsTypeController::class);
        Route::any('goods.php', Controllers\GoodsController::class);
        Route::any('group_buy.php', Controllers\GroupBuyController::class);
        Route::any('guest_stats.php', Controllers\GuestStatsController::class);
        Route::any('help.php', Controllers\HelpController::class);
        Route::any('index.php', Controllers\IndexController::class);
        Route::any('integrate.php', Controllers\IntegrateController::class);
        Route::any('license.php', Controllers\LicenseController::class);
        Route::any('magazine_list.php', Controllers\MagazineListController::class);
        Route::any('mail_template.php', Controllers\MailTemplateController::class);
        Route::any('message.php', Controllers\MessageController::class);
        Route::any('navigator.php', Controllers\NavigatorController::class);
        Route::any('order_stats.php', Controllers\OrderStatsController::class);
        Route::any('order.php', Controllers\OrderController::class);
        Route::any('pack.php', Controllers\PackController::class);
        Route::any('package.php', Controllers\PackageController::class);
        Route::any('payment.php', Controllers\PaymentController::class);
        Route::any('picture_batch.php', Controllers\PictureBatchController::class);
        Route::any('privilege.php', Controllers\PrivilegeController::class);
        Route::any('reg_fields.php', Controllers\RegFieldsController::class);
        Route::any('role.php', Controllers\RoleController::class);
        Route::any('sale_general.php', Controllers\SaleGeneralController::class);
        Route::any('sale_list.php', Controllers\SaleListController::class);
        Route::any('sale_order.php', Controllers\SaleOrderController::class);
        Route::any('search_log.php', Controllers\SearchLogController::class);
        Route::any('searchengine_stats.php', Controllers\SearchEngineStatsController::class);
        Route::any('shipping_area.php', Controllers\ShippingAreaController::class);
        Route::any('shipping.php', Controllers\ShippingController::class);
        Route::any('shop_config.php', Controllers\ShopConfigController::class);
        Route::any('shophelp.php', Controllers\ShopHelpController::class);
        Route::any('shopinfo.php', Controllers\ShopInfoController::class);
        Route::any('sitemap.php', Controllers\SitemapController::class);
        Route::any('sms.php', Controllers\SmsController::class);
        Route::any('snatch.php', Controllers\SnatchController::class);
        Route::any('sql.php', Controllers\SqlController::class);
        Route::any('suppliers_goods.php', Controllers\SuppliersGoodsController::class);
        Route::any('suppliers.php', Controllers\SuppliersController::class);
        Route::any('tag_manage.php', Controllers\TagManageController::class);
        Route::any('template.php', Controllers\TemplateController::class);
        Route::any('topic.php', Controllers\TopicController::class);
        Route::any('user_account_manage.php', Controllers\UserAccountManageController::class);
        Route::any('user_account.php', Controllers\UserAccountController::class);
        Route::any('user_msg.php', Controllers\UserMsgController::class);
        Route::any('user_rank.php', Controllers\UserRankController::class);
        Route::any('users_order.php', Controllers\UsersOrderController::class);
        Route::any('users.php', Controllers\UsersController::class);
        Route::any('view_sendlist.php', Controllers\ViewSendlistController::class);
        Route::any('virtual_card.php', Controllers\VirtualCardController::class);
        Route::any('visit_sold.php', Controllers\VisitSoldController::class);
        Route::any('vote.php', Controllers\VoteController::class);
        Route::any('wholesale.php', Controllers\WholesaleController::class);
    });
});
