<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group('user', function () {
    Route::post('/', 'IndexController@index');
    Route::get('login', 'PassportController@showLoginForm');
    Route::post('login', 'PassportController@login');
    Route::get('forget', 'PassportController@showForgetForm');
    Route::post('forget', 'PassportController@forget');
    Route::get('reset', 'PassportController@showResetForm');
    Route::post('reset', 'PassportController@reset');
})->namespace('app\modules\user\controller');
