<?php

// ==========================================================================
// Code generated by gen:module:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// user route start
Route::prefix('user')->middleware('web')->name('user.')->group(function () {
    // 登录接口
    Route::get('login', [\App\Modules\User\Controllers\LoginController::class, 'showForm'])->name('login');
});
// end
