<?php

// ==========================================================================
// Code generated by module:gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use App\Modules\Webpage\Http\Controllers\IndexController;
use Illuminate\Support\Facades\Route;

// webpage route start
Route::prefix('webpage')->group(function () {
    // 首页
    Route::get('/', [IndexController::class, 'index'])->name('index');
});
// end
