<?php

declare(strict_types=1);

namespace app\modules\admin\request\user;

use OpenApi\Attributes as OA;
use think\Validate;

#[OA\Schema(
    schema: 'UserCreateRequest',
    required: [
        'id',
        'email',
        'user_name',
        'password',
        'question',
        'answer',
        'sex',
        'birthday',
        'user_money',
        'frozen_money',
        'pay_points',
        'rank_points',
        'address_id',
        'reg_time',
        'last_login',
        'last_time',
        'last_ip',
        'visit_count',
        'user_rank',
        'is_special',
        'ec_salt',
        'salt',
        'parent_id',
        'flag',
        'alias',
        'msn',
        'qq',
        'office_phone',
        'home_phone',
        'mobile_phone',
        'is_validated',
        'credit_line',
        'passwd_question',
        'passwd_answer',
        'created_time',
        'updated_time',
        'deleted_time',
    ],
    properties: [
        new OA\Property(property: 'id', description: '用户ID', type: 'integer'),
        new OA\Property(property: 'email', description: '电子邮箱', type: 'string'),
        new OA\Property(property: 'user_name', description: '用户名', type: 'string'),
        new OA\Property(property: 'password', description: '登录密码', type: 'string'),
        new OA\Property(property: 'question', description: '安全问题', type: 'string'),
        new OA\Property(property: 'answer', description: '安全问题答案', type: 'string'),
        new OA\Property(property: 'sex', description: '性别(0未知 1男 2女)', type: 'integer'),
        new OA\Property(property: 'birthday', description: '生日', type: 'string'),
        new OA\Property(property: 'user_money', description: '用户资金', type: 'float'),
        new OA\Property(property: 'frozen_money', description: '冻结资金', type: 'float'),
        new OA\Property(property: 'pay_points', description: '消费积分', type: 'integer'),
        new OA\Property(property: 'rank_points', description: '等级积分', type: 'integer'),
        new OA\Property(property: 'address_id', description: '默认地址ID', type: 'integer'),
        new OA\Property(property: 'reg_time', description: '注册时间戳', type: 'integer'),
        new OA\Property(property: 'last_login', description: '最后登录时间戳', type: 'integer'),
        new OA\Property(property: 'last_time', description: '最后活动时间', type: 'string'),
        new OA\Property(property: 'last_ip', description: '最后登录IP', type: 'string'),
        new OA\Property(property: 'visit_count', description: '访问次数', type: 'integer'),
        new OA\Property(property: 'user_rank', description: '用户等级', type: 'integer'),
        new OA\Property(property: 'is_special', description: '是否特殊用户', type: 'integer'),
        new OA\Property(property: 'ec_salt', description: '加密盐值', type: 'string'),
        new OA\Property(property: 'salt', description: '密码盐值', type: 'string'),
        new OA\Property(property: 'parent_id', description: '推荐人ID', type: 'integer'),
        new OA\Property(property: 'flag', description: '用户标记', type: 'integer'),
        new OA\Property(property: 'alias', description: '昵称', type: 'string'),
        new OA\Property(property: 'msn', description: 'MSN账号', type: 'string'),
        new OA\Property(property: 'qq', description: 'QQ号码', type: 'string'),
        new OA\Property(property: 'office_phone', description: '办公电话', type: 'string'),
        new OA\Property(property: 'home_phone', description: '家庭电话', type: 'string'),
        new OA\Property(property: 'mobile_phone', description: '手机号码', type: 'string'),
        new OA\Property(property: 'is_validated', description: '是否已验证', type: 'integer'),
        new OA\Property(property: 'credit_line', description: '信用额度', type: 'float'),
        new OA\Property(property: 'passwd_question', description: '密码提示问题', type: 'string'),
        new OA\Property(property: 'passwd_answer', description: '密码提示答案', type: 'string'),
        new OA\Property(property: 'created_time', description: '创建时间', type: 'string'),
        new OA\Property(property: 'updated_time', description: '更新时间', type: 'string'),
        new OA\Property(property: 'deleted_time', description: '删除时间', type: 'string'),
    ]
)]
class UserCreateRequest extends Validate
{
    protected $rule = [
        'id' => 'require',
        'email' => 'require',
        'user_name' => 'require',
        'password' => 'require',
        'question' => 'require',
        'answer' => 'require',
        'sex' => 'require',
        'birthday' => 'require',
        'user_money' => 'require',
        'frozen_money' => 'require',
        'pay_points' => 'require',
        'rank_points' => 'require',
        'address_id' => 'require',
        'reg_time' => 'require',
        'last_login' => 'require',
        'last_time' => 'require',
        'last_ip' => 'require',
        'visit_count' => 'require',
        'user_rank' => 'require',
        'is_special' => 'require',
        'ec_salt' => 'require',
        'salt' => 'require',
        'parent_id' => 'require',
        'flag' => 'require',
        'alias' => 'require',
        'msn' => 'require',
        'qq' => 'require',
        'office_phone' => 'require',
        'home_phone' => 'require',
        'mobile_phone' => 'require',
        'is_validated' => 'require',
        'credit_line' => 'require',
        'passwd_question' => 'require',
        'passwd_answer' => 'require',
        'created_time' => 'require',
        'updated_time' => 'require',
        'deleted_time' => 'require',
    ];

    protected $message = [
        'id.require' => '请设置用户ID',
        'email.require' => '请设置电子邮箱',
        'user_name.require' => '请设置用户名',
        'password.require' => '请设置登录密码',
        'question.require' => '请设置安全问题',
        'answer.require' => '请设置安全问题答案',
        'sex.require' => '请设置性别(0未知 1男 2女)',
        'birthday.require' => '请设置生日',
        'user_money.require' => '请设置用户资金',
        'frozen_money.require' => '请设置冻结资金',
        'pay_points.require' => '请设置消费积分',
        'rank_points.require' => '请设置等级积分',
        'address_id.require' => '请设置默认地址ID',
        'reg_time.require' => '请设置注册时间戳',
        'last_login.require' => '请设置最后登录时间戳',
        'last_time.require' => '请设置最后活动时间',
        'last_ip.require' => '请设置最后登录IP',
        'visit_count.require' => '请设置访问次数',
        'user_rank.require' => '请设置用户等级',
        'is_special.require' => '请设置是否特殊用户',
        'ec_salt.require' => '请设置加密盐值',
        'salt.require' => '请设置密码盐值',
        'parent_id.require' => '请设置推荐人ID',
        'flag.require' => '请设置用户标记',
        'alias.require' => '请设置昵称',
        'msn.require' => '请设置MSN账号',
        'qq.require' => '请设置QQ号码',
        'office_phone.require' => '请设置办公电话',
        'home_phone.require' => '请设置家庭电话',
        'mobile_phone.require' => '请设置手机号码',
        'is_validated.require' => '请设置是否已验证',
        'credit_line.require' => '请设置信用额度',
        'passwd_question.require' => '请设置密码提示问题',
        'passwd_answer.require' => '请设置密码提示答案',
        'created_time.require' => '请设置创建时间',
        'updated_time.require' => '请设置更新时间',
        'deleted_time.require' => '请设置删除时间',
    ];
}
