<?php

// ==========================================================================
// Code generated by gen:module:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use Illuminate\Support\Facades\Route;

// shop route start
Route::prefix('shop')->middleware('web')->name('shop.')->group(function () {
});
// end
