<?php

declare(strict_types=1);

namespace app\modules\admin\request\goods;

use OpenApi\Attributes as OA;
use think\Validate;

#[OA\Schema(
    schema: 'GoodsCreateRequest',
    required: [
        'id',
        'cat_id',
        'goods_sn',
        'goods_name',
        'goods_name_style',
        'click_count',
        'brand_id',
        'provider_name',
        'goods_number',
        'goods_weight',
        'market_price',
        'shop_price',
        'promote_price',
        'promote_start_date',
        'promote_end_date',
        'warn_number',
        'keywords',
        'goods_brief',
        'goods_desc',
        'goods_thumb',
        'goods_img',
        'original_img',
        'is_real',
        'extension_code',
        'is_on_sale',
        'is_alone_sale',
        'is_shipping',
        'integral',
        'add_time',
        'sort_order',
        'is_delete',
        'is_best',
        'is_new',
        'is_hot',
        'is_promote',
        'bonus_type_id',
        'last_update',
        'goods_type',
        'seller_note',
        'give_integral',
        'rank_integral',
        'supplier_id',
        'is_check',
        'created_time',
        'updated_time',
        'deleted_time',
    ],
    properties: [
        new OA\Property(property: 'id', description: '商品ID', type: 'integer'),
        new OA\Property(property: 'cat_id', description: '商品分类ID', type: 'integer'),
        new OA\Property(property: 'goods_sn', description: '商品货号', type: 'string'),
        new OA\Property(property: 'goods_name', description: '商品名称', type: 'string'),
        new OA\Property(property: 'goods_name_style', description: '商品名称样式', type: 'string'),
        new OA\Property(property: 'click_count', description: '点击次数', type: 'integer'),
        new OA\Property(property: 'brand_id', description: '品牌ID', type: 'integer'),
        new OA\Property(property: 'provider_name', description: '供应商名称', type: 'string'),
        new OA\Property(property: 'goods_number', description: '库存数量', type: 'integer'),
        new OA\Property(property: 'goods_weight', description: '商品重量(kg)', type: 'float'),
        new OA\Property(property: 'market_price', description: '市场价', type: 'float'),
        new OA\Property(property: 'shop_price', description: '本店售价', type: 'float'),
        new OA\Property(property: 'promote_price', description: '促销价格', type: 'float'),
        new OA\Property(property: 'promote_start_date', description: '促销开始时间', type: 'integer'),
        new OA\Property(property: 'promote_end_date', description: '促销结束时间', type: 'integer'),
        new OA\Property(property: 'warn_number', description: '库存警告数量', type: 'integer'),
        new OA\Property(property: 'keywords', description: '商品关键词', type: 'string'),
        new OA\Property(property: 'goods_brief', description: '商品简介', type: 'string'),
        new OA\Property(property: 'goods_desc', description: '商品详细描述', type: 'string'),
        new OA\Property(property: 'goods_thumb', description: '商品缩略图', type: 'string'),
        new OA\Property(property: 'goods_img', description: '商品图片', type: 'string'),
        new OA\Property(property: 'original_img', description: '商品原图', type: 'string'),
        new OA\Property(property: 'is_real', description: '是否实物商品(1是 0否)', type: 'integer'),
        new OA\Property(property: 'extension_code', description: '商品扩展代码', type: 'string'),
        new OA\Property(property: 'is_on_sale', description: '是否上架(1是 0否)', type: 'integer'),
        new OA\Property(property: 'is_alone_sale', description: '是否单独销售(1是 0否)', type: 'integer'),
        new OA\Property(property: 'is_shipping', description: '是否免运费(1是 0否)', type: 'integer'),
        new OA\Property(property: 'integral', description: '积分购买金额', type: 'integer'),
        new OA\Property(property: 'add_time', description: '添加时间', type: 'integer'),
        new OA\Property(property: 'sort_order', description: '排序权重', type: 'integer'),
        new OA\Property(property: 'is_delete', description: '是否删除(1是 0否)', type: 'integer'),
        new OA\Property(property: 'is_best', description: '是否精品(1是 0否)', type: 'integer'),
        new OA\Property(property: 'is_new', description: '是否新品(1是 0否)', type: 'integer'),
        new OA\Property(property: 'is_hot', description: '是否热销(1是 0否)', type: 'integer'),
        new OA\Property(property: 'is_promote', description: '是否促销(1是 0否)', type: 'integer'),
        new OA\Property(property: 'bonus_type_id', description: '红包类型ID', type: 'integer'),
        new OA\Property(property: 'last_update', description: '最后更新时间', type: 'integer'),
        new OA\Property(property: 'goods_type', description: '商品类型ID', type: 'integer'),
        new OA\Property(property: 'seller_note', description: '商家备注', type: 'string'),
        new OA\Property(property: 'give_integral', description: '赠送积分', type: 'integer'),
        new OA\Property(property: 'rank_integral', description: '等级积分', type: 'integer'),
        new OA\Property(property: 'supplier_id', description: '供应商ID', type: 'integer'),
        new OA\Property(property: 'is_check', description: '是否审核(1是 0否)', type: 'integer'),
        new OA\Property(property: 'created_time', description: '创建时间', type: 'string'),
        new OA\Property(property: 'updated_time', description: '更新时间', type: 'string'),
        new OA\Property(property: 'deleted_time', description: '删除时间', type: 'string'),
    ]
)]
class GoodsCreateRequest extends Validate
{
    protected $rule = [
        'id' => 'require',
        'cat_id' => 'require',
        'goods_sn' => 'require',
        'goods_name' => 'require',
        'goods_name_style' => 'require',
        'click_count' => 'require',
        'brand_id' => 'require',
        'provider_name' => 'require',
        'goods_number' => 'require',
        'goods_weight' => 'require',
        'market_price' => 'require',
        'shop_price' => 'require',
        'promote_price' => 'require',
        'promote_start_date' => 'require',
        'promote_end_date' => 'require',
        'warn_number' => 'require',
        'keywords' => 'require',
        'goods_brief' => 'require',
        'goods_desc' => 'require',
        'goods_thumb' => 'require',
        'goods_img' => 'require',
        'original_img' => 'require',
        'is_real' => 'require',
        'extension_code' => 'require',
        'is_on_sale' => 'require',
        'is_alone_sale' => 'require',
        'is_shipping' => 'require',
        'integral' => 'require',
        'add_time' => 'require',
        'sort_order' => 'require',
        'is_delete' => 'require',
        'is_best' => 'require',
        'is_new' => 'require',
        'is_hot' => 'require',
        'is_promote' => 'require',
        'bonus_type_id' => 'require',
        'last_update' => 'require',
        'goods_type' => 'require',
        'seller_note' => 'require',
        'give_integral' => 'require',
        'rank_integral' => 'require',
        'supplier_id' => 'require',
        'is_check' => 'require',
        'created_time' => 'require',
        'updated_time' => 'require',
        'deleted_time' => 'require',
    ];

    protected $message = [
        'id.require' => '请设置商品ID',
        'cat_id.require' => '请设置商品分类ID',
        'goods_sn.require' => '请设置商品货号',
        'goods_name.require' => '请设置商品名称',
        'goods_name_style.require' => '请设置商品名称样式',
        'click_count.require' => '请设置点击次数',
        'brand_id.require' => '请设置品牌ID',
        'provider_name.require' => '请设置供应商名称',
        'goods_number.require' => '请设置库存数量',
        'goods_weight.require' => '请设置商品重量(kg)',
        'market_price.require' => '请设置市场价',
        'shop_price.require' => '请设置本店售价',
        'promote_price.require' => '请设置促销价格',
        'promote_start_date.require' => '请设置促销开始时间',
        'promote_end_date.require' => '请设置促销结束时间',
        'warn_number.require' => '请设置库存警告数量',
        'keywords.require' => '请设置商品关键词',
        'goods_brief.require' => '请设置商品简介',
        'goods_desc.require' => '请设置商品详细描述',
        'goods_thumb.require' => '请设置商品缩略图',
        'goods_img.require' => '请设置商品图片',
        'original_img.require' => '请设置商品原图',
        'is_real.require' => '请设置是否实物商品(1是 0否)',
        'extension_code.require' => '请设置商品扩展代码',
        'is_on_sale.require' => '请设置是否上架(1是 0否)',
        'is_alone_sale.require' => '请设置是否单独销售(1是 0否)',
        'is_shipping.require' => '请设置是否免运费(1是 0否)',
        'integral.require' => '请设置积分购买金额',
        'add_time.require' => '请设置添加时间',
        'sort_order.require' => '请设置排序权重',
        'is_delete.require' => '请设置是否删除(1是 0否)',
        'is_best.require' => '请设置是否精品(1是 0否)',
        'is_new.require' => '请设置是否新品(1是 0否)',
        'is_hot.require' => '请设置是否热销(1是 0否)',
        'is_promote.require' => '请设置是否促销(1是 0否)',
        'bonus_type_id.require' => '请设置红包类型ID',
        'last_update.require' => '请设置最后更新时间',
        'goods_type.require' => '请设置商品类型ID',
        'seller_note.require' => '请设置商家备注',
        'give_integral.require' => '请设置赠送积分',
        'rank_integral.require' => '请设置等级积分',
        'supplier_id.require' => '请设置供应商ID',
        'is_check.require' => '请设置是否审核(1是 0否)',
        'created_time.require' => '请设置创建时间',
        'updated_time.require' => '请设置更新时间',
        'deleted_time.require' => '请设置删除时间',
    ];
}
