<?php

// ==========================================================================
// Code generated by gen:route CLI tool. DO NOT EDIT.
// ==========================================================================

declare(strict_types=1);

use think\facade\Route;

Route::group('shop', function () {
    Route::post('/', 'IndexController@index');
})->namespace('app\api\shop\controller');
